Repository gazebosim/sdformat, pull requests merged in 2020-12, with the labels that each got.

#435 Decrease far clip lower bound
  sdf/1.6/camera.sdf
  sdf/1.7/camera.sdf
Labels: 🏰 citadel

#438 Re-disable tests for #202
  src/SDF_TEST.cc
Labels: 🏰 citadel

#437 Decrease far clip lower bound. Forward port of #435 to sdf10
  sdf/1.6/camera.sdf
  sdf/1.7/camera.sdf
Labels: 🏢 edifice, 🔮 dome

#429 Add lightmap to 1.7 spec and PBR material DOM
  include/sdf/Pbr.hh
  sdf/1.7/material.sdf
  src/Pbr.cc
  src/Pbr_TEST.cc
  test/integration/material_pbr.cc
  test/sdf/material_pbr.sdf
Labels: 🏢 edifice, 🔮 dome

#442 Prepare for 10.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🔮 dome

#450 [backport] Re-disable tests for #202, since they are broken (#438)
  src/SDF_TEST.cc
Labels: 📜 blueprint

#446 Added render_order to material
  include/sdf/Material.hh
  sdf/1.7/material.sdf
  src/Material.cc
  src/Material_TEST.cc
  test/integration/visual_dom.cc
  test/sdf/material.sdf
Labels: 🏢 edifice, 🔮 dome

#449 ⬆️ 8.9.1 🏁
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint
