Repository gazebosim/sdformat, pull requests merged in 2020-11, with the labels that each got.

#403 Cherry-pick #392 to sdf8: Move list of debian dependencies to packages.apt
  .github/ci/packages.apt
  .github/workflows/linux-ubuntu-bionic.yml
Labels: 📜 blueprint

#404 Cherry-pick #392 to sdf10: Move list of debian dependencies to packages.apt
  .github/ci/packages.apt
  .github/workflows/linux-ubuntu-bionic.yml
Labels: 🏢 edifice, 🔮 dome

#402 Remove custom element warning/error
  src/parser.cc
  src/parser_TEST.cc
  test/sdf/custom_and_unknown_elements.sdf
Labels: 🏢 edifice, 🔮 dome

#415 Cherry-pick #414 to sdf9: Enable tests for #202, add macos catalina workflow
  .github/workflows/macos.yml
  src/SDF_TEST.cc
Labels: 🏰 citadel

#397 Add Sky DOM
  include/sdf/CMakeLists.txt
  include/sdf/Scene.hh
  include/sdf/Sky.hh
  src/CMakeLists.txt
  src/Scene.cc
  src/Scene_TEST.cc
  src/Sky.cc
  src/Sky_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/scene_dom.cc
  test/sdf/scene_with_sky.sdf
Labels: 🏢 edifice, 🔮 dome

#410 Add <double_sided> to material spec
  include/sdf/Material.hh
  sdf/1.7/material.sdf
  src/Material.cc
  src/Material_TEST.cc
  test/integration/visual_dom.cc
  test/sdf/material.sdf
Labels: 🏢 edifice, 🔮 dome

#422 Test included model folders missing model.config
  src/parser.cc
  test/integration/includes.cc
  test/integration/model/box_missing_config/model.sdf
Labels: 🏰 citadel

#424 Backport #399 to sdf9: Prefix nested model names when flattening
  src/parser.cc
  test/integration/model/test_model_with_frames/model.sdf
  test/integration/nested_model_with_frames_expected.sdf
  test/integration/two_level_nested_model_with_frames_expected.sdf
Labels: 🏰 citadel

#417 Backport Sky DOM
  include/sdf/CMakeLists.txt
  include/sdf/Scene.hh
  include/sdf/Sky.hh
  src/CMakeLists.txt
  src/Scene.cc
  src/Scene_TEST.cc
  src/Sky.cc
  src/Sky_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/scene_dom.cc
  test/sdf/scene_with_sky.sdf
Labels: 🏰 citadel
