Repository gazebosim/sdformat, pull requests merged in 2020-09, with the labels that each got.

#341 Support implicit nested canonical links
  Changelog.md
  Migration.md
  include/sdf/Model.hh
  src/FrameSemantics.cc
  src/Model.cc
  src/ign_TEST.cc
  test/integration/model_dom.cc
  test/sdf/model_canonical_link.sdf
  test/sdf/nested_canonical_link.sdf
  test/sdf/nested_invalid_explicit_canonical_link.sdf
Labels: 🏰 citadel

#348 Add cmake option to disable console logfile
  CMakeLists.txt
  cmake/sdf_config.h.in
  include/sdf/Console.hh
  src/Console.cc
Labels: 🔮 dome

#356 Cherry-pick to sdf10: Store material file path information
  include/sdf/Material.hh
  src/Material.cc
  src/Material_TEST.cc
Labels: 🔮 dome

#362 Cherry-pick to sdf8: Collection labeler
  .github/workflows/pr-collection-labeler.yml
Labels: 📜 blueprint

#364 Cherry-pick to sdf10: Collection labeler
  .github/workflows/pr-collection-labeler.yml
Labels: 🔮 dome

#363 Cherry-pick to sdf9: Collection labeler
  .github/workflows/pr-collection-labeler.yml
Labels: 🏰 citadel

#245 SearchForStuff: add logic to find urdfdom without pkg-config
  cmake/SearchForStuff.cmake
Labels: 🏰 citadel

#369 Define PATH_MAX for Debian Hurd system
  src/Filesystem.cc
  src/Filesystem_TEST.cc
Labels: 🏰 citadel

#359 Fix whitespace preservation behavior with TinyXML2
  src/parser.cc
  src/parser_urdf_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/whitespace.cc
  test/sdf/whitespace.sdf
Labels: beta, 🔮 dome

#357 Return positive infinity instead of -1 for boundless positive values
  include/sdf/JointAxis.hh
  src/JointAxis.cc
  src/JointAxis_TEST.cc
  src/Utils.cc
  src/Utils.hh
  test/integration/joint_axis_dom.cc
  test/sdf/joint_axis_infinite_limits.sdf
Labels: beta, 🔮 dome
