Repository gazebosim/sdformat, pull requests merged in 2021-07, with the labels that each got.

#602 Add World::ValidateGraphs method (sdf9)
  include/sdf/Model.hh
  include/sdf/World.hh
  src/FrameSemantics.cc
  src/Model.cc
  src/Model_TEST.cc
  src/World.cc
  src/World_TEST.cc
  test/integration/frame.cc
  test/integration/model_dom.cc
  test/integration/world_dom.cc
Labels: 🏰 citadel

#601 Add World::ValidateGraphs method
  include/sdf/Model.hh
  include/sdf/World.hh
  src/FrameSemantics.cc
  src/Model.cc
  src/Model_TEST.cc
  src/World.cc
  src/World_TEST.cc
  test/integration/frame.cc
  test/integration/model_dom.cc
  test/integration/world_dom.cc
Labels: 🏢 edifice

#614 Merge 9 -> 10
  include/sdf/Model.hh
  include/sdf/World.hh
  src/FrameSemantics.cc
  src/Model.cc
  src/Model_TEST.cc
  src/World.cc
  src/World_TEST.cc
  test/integration/frame.cc
  test/integration/model_dom.cc
  test/integration/world_dom.cc
Labels: 🔮 dome

#615 Merge 9 -> 11
  include/sdf/Element.hh
  src/Element.cc
  src/Element_TEST.cc
  test/integration/default_elements.cc
  test/sdf/empty_road_sph_coords.sdf
Labels: 🏢 edifice

#616 🎈 11.2.2
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#620 Add Element::FindElement as an alternative to Element::GetElement
  Migration.md
  include/sdf/Element.hh
  src/Element.cc
  src/Element_TEST.cc
Labels: 🏰 citadel

#623 Error: move << operator from .hh to .cc file
  include/sdf/Error.hh
  src/Error.cc
Labels: 🏢 edifice

#621 Update build system to allow overriding CXX flags and using clang on Linux
  CMakeLists.txt
  cmake/DefaultCFlags.cmake
Labels: 🏰 citadel

#624 10 ➡️ 11
  sdf/1.6/particle_emitter.sdf
  src/CMakeLists.txt
  src/ParamPassing.cc
  src/ParamPassing.hh
  src/ParamPassing_TEST.cc
  src/parser.cc
  src/parser_private.hh
  test/integration/CMakeLists.txt
  test/integration/include_custom_model.sdf
  test/integration/include_custom_model_expected_output.sdf
  test/integration/include_custom_nested_model_expected_output.sdf
  test/integration/include_invalid_custom_model.sdf
  test/integration/include_model.sdf
  test/integration/model/nested_include/base/base.sdf
  test/integration/model/nested_include/base/model.config
  test/integration/model/nested_include/test_nested_include.sdf
  test/integration/model/nested_include/top_camera/model.config
  test/integration/model/nested_include/top_camera/top_camera.sdf
  test/integration/model/nested_include/top_model/model.config
  test/integration/model/nested_include/top_model/top_model.sdf
  test/integration/model/nested_include/wheel/model.config
  test/integration/model/nested_include/wheel/wheel.sdf
  test/integration/model/robot/model.config
  test/integration/model/robot/model.sdf
  test/integration/param_passing.cc
Labels: 🏢 edifice

#625 Error: move << operator from .hh to .cc file (backport to sdf9)
  include/sdf/Error.hh
  src/Error.cc
Labels: 🏰 citadel

#619 Emit an error instead of a warning when a file has multiple root level model, actor or light elements
  Migration.md
  include/sdf/Root.hh
  src/Root.cc
  src/Root_TEST.cc
  src/parser.cc
  test/integration/model/nested_multiple_actors_error/model.sdf
  test/integration/model/nested_multiple_elements_error/model.sdf
  test/integration/model/nested_multiple_lights_error/model.sdf
  test/integration/model/nested_multiple_models_error/model.sdf
  test/integration/nested_multiple_elements_error.cc
  test/integration/root_dom.cc
Labels: 🏯 fortress

#622 Remove deprecated functions and classes
  Migration.md
  include/sdf/Element.hh
  include/sdf/JointAxis.hh
  include/sdf/Types.hh
  sdf/1.9/1_8.convert
  sdf/1.9/joint.sdf
  src/Element.cc
  src/Element_TEST.cc
  src/JointAxis.cc
  src/JointAxis_TEST.cc
  test/integration/joint_axis_dom.cc
Labels: 🏯 fortress

#627 11 ➡️ 12 Forward port
  Changelog.md
  include/sdf/Element.hh
  include/sdf/Error.hh
  include/sdf/Model.hh
  include/sdf/World.hh
  sdf/1.6/particle_emitter.sdf
  src/CMakeLists.txt
  src/Element.cc
  src/Element_TEST.cc
  src/Error.cc
  src/FrameSemantics.cc
  src/Model.cc
  src/Model_TEST.cc
  src/ParamPassing.cc
  src/ParamPassing.hh
  src/ParamPassing_TEST.cc
  src/World.cc
  src/World_TEST.cc
  src/parser.cc
  src/parser_private.hh
  test/integration/CMakeLists.txt
  test/integration/default_elements.cc
  test/integration/frame.cc
  test/integration/include_custom_model.sdf
  test/integration/include_custom_model_expected_output.sdf
  test/integration/include_custom_nested_model_expected_output.sdf
  test/integration/include_invalid_custom_model.sdf
  test/integration/include_model.sdf
  test/integration/model/nested_include/base/base.sdf
  test/integration/model/nested_include/base/model.config
  test/integration/model/nested_include/test_nested_include.sdf
  test/integration/model/nested_include/top_camera/model.config
  test/integration/model/nested_include/top_camera/top_camera.sdf
  test/integration/model/nested_include/top_model/model.config
  test/integration/model/nested_include/top_model/top_model.sdf
  test/integration/model/nested_include/wheel/model.config
  test/integration/model/nested_include/wheel/wheel.sdf
  test/integration/model/robot/model.config
  test/integration/model/robot/model.sdf
  test/integration/model_dom.cc
  test/integration/param_passing.cc
  test/integration/world_dom.cc
  test/sdf/empty_road_sph_coords.sdf
Labels: 🏯 fortress

#630 Minor fix to Migration guide
  Migration.md
Labels: 🏰 citadel

#631 BUG: add missing sdf files to CMakeLists
  sdf/1.6/CMakeLists.txt
  sdf/1.7/CMakeLists.txt
  sdf/1.8/CMakeLists.txt
Labels: 🏢 edifice

#644 updated material spec
  sdf/1.6/material.sdf
  sdf/1.7/material.sdf
Labels: 🏰 citadel
