Repository gazebosim/sdformat, pull requests merged in 2021-05, with the labels that each got.

#562 Fix bug where included URDFs are not parsed when there are no custom parsers
  src/parser.cc
  test/integration/includes.cc
  test/integration/model/test_include_urdf/model.config
  test/integration/model/test_include_urdf/model.urdf
Labels: 🏢 edifice

#547 Add scatter ratio parameter to Particle Emitter DOM
  include/sdf/ParticleEmitter.hh
  sdf/1.7/particle_emitter.sdf
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  test/integration/particle_emitter_dom.cc
  test/sdf/world_complete.sdf
Labels: 🔮 dome

#551 parser: Use encapsulated string constants for non-file sources
  include/sdf/Types.hh
  src/parser.cc
  src/parser_TEST.cc
Labels: 🏢 edifice

#569 Prepare for 10.5.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#542 adding element default check
  include/sdf/Element.hh
  src/Element.cc
  src/Element_TEST.cc
  src/parser.cc
  test/integration/CMakeLists.txt
  test/integration/default_elements.cc
  test/sdf/empty_axis.sdf
  test/sdf/empty_road_sph_coords.sdf
  tools/code_check.sh
Labels: 🏰 citadel

#570 Merge sdf 1.7 changes forward to 1.8
  sdf/1.8/camera.sdf
  sdf/1.8/frame.sdf
  sdf/1.8/material.sdf
  sdf/1.8/sensor.sdf
  sdf/1.8/surface.sdf
Labels: 🏢 edifice

#548 Encode XML path and line number in Element and add XML path setter Error.
  include/sdf/Element.hh
  include/sdf/Error.hh
  src/Element.cc
  src/Element_TEST.cc
  src/Error.cc
  src/Error_TEST.cc
  src/Types_TEST.cc
  src/Utils.cc
  src/Utils_TEST.cc
  src/parser.cc
  src/parser_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/element_tracing.cc
Labels: 🏢 edifice

#526 Allow to convert URDF color to SDF material tag
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction_collision_visual_extension.urdf
  test/integration/material.cc
  test/sdf/material_valid.urdf
Labels: 🏢 edifice

#576 11 ➡️ main
  Changelog.md
  include/sdf/Element.hh
  include/sdf/Error.hh
  sdf/1.8/camera.sdf
  sdf/1.8/frame.sdf
  sdf/1.8/material.sdf
  sdf/1.8/sensor.sdf
  sdf/1.8/surface.sdf
  src/Element.cc
  src/Element_TEST.cc
  src/Error.cc
  src/Error_TEST.cc
  src/Types_TEST.cc
  src/Utils.cc
  src/Utils_TEST.cc
  src/parser.cc
  src/parser_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/element_tracing.cc
  test/integration/includes.cc
  test/integration/model/test_include_urdf/model.config
  test/integration/model/test_include_urdf/model.urdf
Labels: 🏯 fortress
