Repository gazebosim/sdformat, pull requests merged in 2021-01, with the labels that each got.

#388 Add Heightmap class
  include/sdf/CMakeLists.txt
  include/sdf/Geometry.hh
  include/sdf/Heightmap.hh
  src/CMakeLists.txt
  src/Geometry.cc
  src/Heightmap.cc
  src/Heightmap_TEST.cc
  test/integration/geometry_dom.cc
  test/sdf/shapes.sdf
Labels: 🏰 citadel

#456 Disable ign tests on Windows (sdf10)
  cmake/SearchForStuff.cmake
  src/CMakeLists.txt
  src/ign_TEST.cc
Labels: 🏢 edifice, 🔮 dome

#441 Bump to 9.4.0
  .github/workflows/macos.yml
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🏰 citadel

#458 9 ➡️ 10
  include/sdf/CMakeLists.txt
  include/sdf/Geometry.hh
  include/sdf/Heightmap.hh
  src/CMakeLists.txt
  src/Geometry.cc
  src/Heightmap.cc
  src/Heightmap_TEST.cc
  test/integration/geometry_dom.cc
  test/sdf/shapes.sdf
Labels: 🏢 edifice, 🔮 dome

#461 ⬆️ 10.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🔮 dome

#448 Allow files paths for include URIs
  sdf/1.8/model.sdf
  sdf/1.8/world.sdf
  src/parser.cc
  test/integration/includes.cc
  test/sdf/includes.sdf
Labels: enhancement, 🏢 edifice

#465 Changelog: remove duplicate entries from 10.2.0
  Changelog.md
Labels: 🔮 dome

#466 Prepare for 11.0.0~pre1
  Changelog.md
Labels: 🏢 edifice

#471 Merge 10 -> 11 and disable more ign tests on windows
  Changelog.md
  src/ign_TEST.cc
Labels: 🏢 edifice

#460 Replace PROJECT_SOURCE_DIR in tests
  src/CMakeLists.txt
  src/Converter_TEST.cc
  src/FrameSemantics_TEST.cc
  src/ign_TEST.cc
  src/parser_TEST.cc
  test/env.hh
  test/integration/actor_dom.cc
  test/integration/audio.cc
  test/integration/cfm_damping_implicit_spring_damper.cc
  test/integration/collision_dom.cc
  test/integration/converter.cc
  test/integration/disable_fixed_joint_reduction.cc
  test/integration/element_memory_leak.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/force_torque_sensor.cc
  test/integration/frame.cc
  test/integration/geometry_dom.cc
  test/integration/include.cc
  test/integration/includes.cc
  test/integration/joint_axis_dom.cc
  test/integration/joint_dom.cc
  test/integration/light_dom.cc
  test/integration/link_dom.cc
  test/integration/material_pbr.cc
  test/integration/model_dom.cc
  test/integration/model_versions.cc
  test/integration/plugin_include.cc
  test/integration/provide_feedback.cc
  test/integration/root_dom.cc
  test/integration/scene_dom.cc
  test/integration/sdf_custom.cc
  test/integration/surface_dom.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_joint_parameters.cc
  test/integration/visual_dom.cc
  test/integration/whitespace.cc
  test/integration/world_dom.cc
  test/performance/parser_urdf.cc
  test/test_config.h.in
Labels: 🏢 edifice, 🔮 dome

#463 Add Windows installation
  README.md
Labels: 🏰 citadel

#472 Change all std::unique_ptr members of *Private classes to std::optional
  src/Geometry.cc
  src/Joint.cc
  src/Material.cc
  src/Scene.cc
  src/Sensor.cc
  src/Utils.hh
  src/Visual.cc
  src/World.cc
Labels: 🏢 edifice

#454 Add laser_retro in Visual
  include/sdf/Visual.hh
  src/Visual.cc
  src/Visual_TEST.cc
  test/integration/visual_dom.cc
  test/sdf/shapes.sdf
Labels: 🏰 citadel

#459 Reduce default heightmap sampling from 2 to 1
  Migration.md
  include/sdf/Heightmap.hh
  sdf/1.8/heightmap_shape.sdf
  src/Heightmap.cc
  src/Heightmap_TEST.cc
Labels: 🏢 edifice

#457 Add split/join for separating the link name from it's fully qualified name
  include/sdf/Types.hh
  src/Types.cc
  src/Types_TEST.cc
Labels: 🏢 edifice
