Repository gazebosim/sdformat, pull requests merged in 2021-03, with the labels that each got.

#486 Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🏢 edifice

#503 ign-utils -> ign-utils1
  .github/ci/packages.apt
Labels: 🏢 edifice

#506 Fix lidar resolution description about interpolation
  sdf/1.6/lidar.sdf
  sdf/1.7/lidar.sdf
  sdf/1.8/lidar.sdf
Labels: 🏢 edifice

#507 10 ➡️ 11
  Changelog.md
  sdf/1.7/camera.sdf
  src/Camera.cc
Labels: 🏢 edifice

#501 👩‍🌾 Backport action-ignition-ci (#452)
  .github/ci/after_make_test.sh
  .github/ci/between_cmake_make.sh
  .github/workflows/ci.yml
  .github/workflows/linux-ubuntu-bionic.yml
Labels: 🏰 citadel

#511 9 ➡️ 10
  .github/ci/after_make_test.sh
  .github/ci/between_cmake_make.sh
  .github/workflows/ci.yml
  .github/workflows/linux-ubuntu-bionic.yml
Labels: 🔮 dome

#514 Add camera type aliases to docs
  sdf/1.6/sensor.sdf
  sdf/1.7/sensor.sdf
Labels: 🏰 citadel

#516 9 to 10
  sdf/1.6/sensor.sdf
  sdf/1.7/sensor.sdf
Labels: 🔮 dome

#520 10 ➡️ 11
  .github/ci/after_make_test.sh
  .github/workflows/ci.yml
  sdf/1.6/sensor.sdf
  sdf/1.7/sensor.sdf
Labels: beta, 🏢 edifice

#504 Unflatten flattened models
  sdf/1.8/1_7.convert
  src/Converter.cc
  src/Converter.hh
  src/Converter_TEST.cc
  src/XmlUtils.cc
  src/XmlUtils.hh
  test/integration/converter.cc
  test/integration/nested_model.cc
  test/sdf/flattened_test_nested_model_with_frames.sdf
Labels: beta, 🏢 edifice

#515 Error when delimiter "::" found in element name in SDFormat 1.8
  Migration.md
  include/sdf/parser.hh
  src/parser.cc
  src/parser_TEST.cc
Labels: beta, 🏢 edifice

#512 Include file path and line number in parsing errors
  include/sdf/Error.hh
  src/Error.cc
  src/Error_TEST.cc
  src/Utils.cc
  src/Utils.hh
  src/Utils_TEST.cc
  src/ign.cc
  src/ign_TEST.cc
  src/parser.cc
  src/parser_TEST.cc
  src/parser_private.hh
  test/integration/model/model_without_top_level/model.config
  test/integration/model/model_without_top_level/model.sdf
  test/sdf/includes_missing_model.sdf
  test/sdf/includes_missing_uri.sdf
  test/sdf/includes_model_without_sdf.sdf
  test/sdf/includes_without_top_level.sdf
Labels: beta, 🏢 edifice

#521 Improve docs of collision_bitmask.
  sdf/1.4/surface.sdf
  sdf/1.5/surface.sdf
  sdf/1.6/surface.sdf
  sdf/1.7/surface.sdf
Labels: 🏰 citadel

#518 Add nested model support for World's `*ByName` and `*NameExists` functions
  include/sdf/World.hh
  src/World.cc
  src/World_TEST.cc
  test/integration/model_dom.cc
  test/integration/world_dom.cc
  test/sdf/nested_model.sdf
  test/sdf/world_nested_frame.sdf
  test/sdf/world_nested_model.sdf
Labels: beta, 🏢 edifice

#519 updated loading //material colors
  src/Param.cc
  src/Param_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/material.cc
  test/sdf/material_invalid.sdf
  test/sdf/material_valid.sdf
Labels: beta, 🏢 edifice

#509 Store include info in Element
  include/sdf/Element.hh
  src/Element.cc
  src/Element_TEST.cc
  src/parser.cc
  test/integration/nested_model.cc
Labels: beta, 🏢 edifice

#517 Add Joint DOM API to access joint sensors
  include/sdf/Joint.hh
  src/Joint.cc
  src/Joint_TEST.cc
  test/integration/joint_dom.cc
  test/sdf/joint_sensors.sdf
Labels: beta, 🏢 edifice

#475 Implement SDFormat 1.8 Interface API
  include/sdf/CMakeLists.txt
  include/sdf/InterfaceElements.hh
  include/sdf/InterfaceFrame.hh
  include/sdf/InterfaceJoint.hh
  include/sdf/InterfaceLink.hh
  include/sdf/InterfaceModel.hh
  include/sdf/InterfaceModelPoseGraph.hh
  include/sdf/Model.hh
  include/sdf/ParserConfig.hh
  include/sdf/Root.hh
  include/sdf/World.hh
  src/CMakeLists.txt
  src/FrameSemantics.cc
  src/FrameSemantics.hh
  src/InterfaceFrame.cc
  src/InterfaceJoint.cc
  src/InterfaceLink.cc
  src/InterfaceModel.cc
  src/InterfaceModelPoseGraph.cc
  src/Model.cc
  src/ParserConfig.cc
  src/Root.cc
  src/ScopedGraph.hh
  src/Types.cc
  src/Utils.cc
  src/Utils.hh
  src/World.cc
  src/parser.cc
  test/integration/CMakeLists.txt
  test/integration/interface_api.cc
  test/integration/model/double_pendulum.toml
  test/integration/toml_parser.hh
  test/sdf/include_with_interface_api_frame_semantics.sdf
  test/sdf/include_with_interface_api_reposture.sdf
  test/sdf/model_include_with_interface_api.sdf
  test/sdf/world_include_with_interface_api.sdf
  test/test_config.h.in
  tools/code_check.sh
Labels: beta, 🏢 edifice

#523 🎈 11.0.0~pre3
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#524 Fix changelog
  Changelog.md
Labels: 🏢 edifice
