Repository gazebosim/sdformat, pull requests merged in 2021-02, with the labels that each got.

#478 Root: Fix minor grammar error in error message
  src/Root.cc
Labels: 🏢 edifice

#482 Fix temperature gradient default value in Atmosphere DOM
  Migration.md
  src/Atmosphere.cc
  src/Atmosphere_TEST.cc
Labels: 🔮 dome

#480 Error when //inertial/pose/@relative_to is non-default
  Migration.md
  sdf/1.8/inertial.sdf
  sdf/Migration.md
  test/integration/link_dom.cc
Labels: 🏢 edifice

#483 Wrap description tags in CDATA
  src/Element.cc
Labels: 🏰 citadel

#439 Add ParserConfig class to encapsulate file path settings
  include/sdf/CMakeLists.txt
  include/sdf/ParserConfig.hh
  include/sdf/Root.hh
  include/sdf/SDFImpl.hh
  include/sdf/parser.hh
  src/CMakeLists.txt
  src/Model_TEST.cc
  src/ParserConfig.cc
  src/ParserConfig_TEST.cc
  src/Root.cc
  src/SDF.cc
  src/SDF_TEST.cc
  src/parser.cc
  src/parser_private.hh
  test/integration/CMakeLists.txt
  test/integration/parser_config.cc
Labels: 🏢 edifice

#484 Added lights intensity field
  include/sdf/Light.hh
  sdf/1.8/light.sdf
  src/Light.cc
  src/Light_TEST.cc
  test/integration/light_dom.cc
  test/sdf/world_complete.sdf
Labels: 🏢 edifice

#481 Add EnforcementPolicy in ParserConfig to enable configurable parsing strictness
  include/sdf/Error.hh
  include/sdf/ParserConfig.hh
  src/ParserConfig.cc
  src/Utils.cc
  src/Utils.hh
  src/parser.cc
  test/integration/unknown.cc
  test/sdf/unrecognized_elements.sdf
  test/sdf/unrecognized_elements_with_namespace.sdf
Labels: 🏢 edifice

#488 Bump to 11.0.0~pre2, Changelog and Migration guide
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🏢 edifice

#489 sdformat.pc.in: requires ignition-utils1
  cmake/sdformat_pc.in
Labels: 🏢 edifice

#491 ⬆️ 9.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#490 tests: Ensure removed SDFormat elements raise errors in newer versions
  test/integration/unknown.cc
Labels: 🏢 edifice

#492 9 ➡️ 10
  Changelog.md
  Migration.md
  README.md
  include/sdf/Visual.hh
  src/Element.cc
  src/Visual.cc
  src/Visual_TEST.cc
  test/integration/visual_dom.cc
  test/sdf/shapes.sdf
Labels: 🔮 dome

#493 Quietly search for urdfdom
  cmake/SearchForStuff.cmake
Labels: 🏢 edifice

#495 10 ➡️ 11
  Changelog.md
  Migration.md
  README.md
  include/sdf/Visual.hh
  src/Atmosphere.cc
  src/Atmosphere_TEST.cc
  src/CMakeLists.txt
  src/Converter_TEST.cc
  src/Element.cc
  src/FrameSemantics_TEST.cc
  src/Visual.cc
  src/Visual_TEST.cc
  src/ign_TEST.cc
  src/parser_TEST.cc
  test/env.hh
  test/integration/actor_dom.cc
  test/integration/audio.cc
  test/integration/cfm_damping_implicit_spring_damper.cc
  test/integration/collision_dom.cc
  test/integration/converter.cc
  test/integration/disable_fixed_joint_reduction.cc
  test/integration/element_memory_leak.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/force_torque_sensor.cc
  test/integration/frame.cc
  test/integration/geometry_dom.cc
  test/integration/include.cc
  test/integration/includes.cc
  test/integration/joint_axis_dom.cc
  test/integration/joint_dom.cc
  test/integration/light_dom.cc
  test/integration/link_dom.cc
  test/integration/material_pbr.cc
  test/integration/model_dom.cc
  test/integration/model_versions.cc
  test/integration/plugin_include.cc
  test/integration/provide_feedback.cc
  test/integration/root_dom.cc
  test/integration/scene_dom.cc
  test/integration/sdf_custom.cc
  test/integration/surface_dom.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_joint_parameters.cc
  test/integration/visual_dom.cc
  test/integration/whitespace.cc
  test/integration/world_dom.cc
  test/performance/parser_urdf.cc
  test/sdf/shapes.sdf
  test/test_config.h.in
Labels: 🏢 edifice

#487 Add L16 pixel format to Camera pixel format conversion function
  sdf/1.7/camera.sdf
  src/Camera.cc
Labels: 🔮 dome

#498 🎈 10.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome
