Repository gazebosim/sdformat, pull requests merged in 2021-08, with the labels that each got.

#636 Fix unreported invalid model when reference frame is unavailable
  src/ign_TEST.cc
  src/parser.cc
  src/parser_private.hh
  test/integration/frame.cc
  test/sdf/model_invalid_top_level_frame.sdf
Labels: 🏢 edifice

#628 Fix urdf link extension tags
  src/SDFExtension.cc
  src/SDFExtension.hh
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_collision_visual_empty_root.sdf
  test/integration/fixed_joint_reduction_collision_visual_extension.sdf
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🏰 citadel

#648 9 ⬅️ 10
  include/sdf/Pbr.hh
  sdf/1.7/material.sdf
  src/Pbr.cc
  src/Pbr_TEST.cc
  test/integration/material_pbr.cc
  test/sdf/material_pbr.sdf
Labels: 🏰 citadel

#638 Support parsing elements that are not part of the schema
  include/sdf/Param.hh
  src/Param.cc
  src/Param_TEST.cc
  test/integration/CMakeLists.txt
Labels: 🏰 citadel

#656 9 ➡️ 10
  CMakeLists.txt
  Migration.md
  cmake/DefaultCFlags.cmake
  include/sdf/Element.hh
  include/sdf/Error.hh
  include/sdf/Param.hh
  sdf/1.6/material.sdf
  sdf/1.7/material.sdf
  src/Element.cc
  src/Element_TEST.cc
  src/Error.cc
  src/Param.cc
  src/Param_TEST.cc
  src/SDFExtension.cc
  src/SDFExtension.hh
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_collision_visual_empty_root.sdf
  test/integration/fixed_joint_reduction_collision_visual_extension.sdf
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🔮 dome

#657 10 ➡️ 11
  CMakeLists.txt
  Migration.md
  cmake/DefaultCFlags.cmake
  include/sdf/Element.hh
  include/sdf/Param.hh
  sdf/1.6/material.sdf
  sdf/1.7/material.sdf
  sdf/1.8/material.sdf
  src/Element.cc
  src/Element_TEST.cc
  src/Param.cc
  src/Param_TEST.cc
  src/SDFExtension.cc
  src/SDFExtension.hh
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_collision_visual_empty_root.sdf
  test/integration/fixed_joint_reduction_collision_visual_extension.sdf
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🏢 edifice

#660 11 ➡️ main
  CMakeLists.txt
  Migration.md
  cmake/DefaultCFlags.cmake
  include/sdf/Element.hh
  include/sdf/Param.hh
  sdf/1.6/CMakeLists.txt
  sdf/1.6/material.sdf
  sdf/1.7/CMakeLists.txt
  sdf/1.7/material.sdf
  sdf/1.8/CMakeLists.txt
  sdf/1.8/material.sdf
  sdf/1.9/CMakeLists.txt
  sdf/1.9/material.sdf
  src/Element.cc
  src/Element_TEST.cc
  src/Param.cc
  src/Param_TEST.cc
  src/SDFExtension.cc
  src/SDFExtension.hh
  src/ign_TEST.cc
  src/parser.cc
  src/parser_private.hh
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_collision_visual_empty_root.sdf
  test/integration/fixed_joint_reduction_collision_visual_extension.sdf
  test/integration/frame.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
  test/sdf/model_invalid_top_level_frame.sdf
Labels: 🏯 fortress

#652 Add support for custom sensors
  include/sdf/Sensor.hh
  sdf/1.9/sensor.sdf
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏯 fortress

#453 Add GPS sensor to sdf9
  .gitignore
  include/sdf/CMakeLists.txt
  include/sdf/NavSat.hh
  include/sdf/Sensor.hh
  sdf/1.7/navsat.sdf
  sdf/1.7/sensor.sdf
  src/CMakeLists.txt
  src/NavSat.cc
  src/NavSat_TEST.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏰 citadel

#662 BUG: make time type string [s ns]
  sdf/1.5/schema/types.xsd
  sdf/1.6/schema/types.xsd
  sdf/1.7/schema/types.xsd
  sdf/1.8/schema/types.xsd
Labels: 🏢 edifice

#665 Adds enable_metrics flag to Sensor.
  include/sdf/Sensor.hh
  sdf/1.7/sensor.sdf
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏰 citadel

#671 🎈 9.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#673 Add pull request triage to sdf9
  .github/workflows/triage.yml
Labels: 🏰 citadel

#592 Add segmentation and bounding box sensor types
  include/sdf/Camera.hh
  include/sdf/Sensor.hh
  sdf/1.9/camera.sdf
  sdf/1.9/sensor.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏯 fortress

#672 9 ➡️ 10
  .github/workflows/triage.yml
  .gitignore
  Changelog.md
  include/sdf/CMakeLists.txt
  include/sdf/NavSat.hh
  include/sdf/Sensor.hh
  sdf/1.7/navsat.sdf
  sdf/1.7/sensor.sdf
  src/CMakeLists.txt
  src/NavSat.cc
  src/NavSat_TEST.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🔮 dome

#674 👩‍🌾 Remove bitbucket-pipelines
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  bitbucket-pipelines.yml
Labels: Gazebo 9️

#675 BUG: add missing plugin element to include
  sdf/1.5/model.sdf
  sdf/1.5/world.sdf
  sdf/1.6/model.sdf
  sdf/1.6/world.sdf
  sdf/1.7/model.sdf
  sdf/1.7/world.sdf
Labels: 🏰 citadel, Gazebo 1️1️

#679 Update Ubuntu install docs
  README.md
Labels: 🏢 edifice
