Repository gazebosim/sdformat, pull requests merged in 2021-12, with the labels that each got.

#729 Fix empty pose parsing fail for rotation_format='quat_xyzw'
  include/sdf/Param.hh
  src/Param.cc
  src/Param_TEST.cc
  src/parser.cc
  test/integration/include_custom_model_expected_output.sdf
  test/integration/pose_1_9_sdf.cc
  test/sdf/pose_1_9.sdf
Labels: 🏯 fortress, 🌱 garden

#765 Added Add & Clear function to World, Model, and Link
  include/sdf/Link.hh
  include/sdf/Model.hh
  include/sdf/World.hh
  sdf/1.9/actor.sdf
  src/Link.cc
  src/Link_TEST.cc
  src/Model.cc
  src/Model_TEST.cc
  src/World.cc
  src/World_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#766 prepare 12.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress, 🌱 garden

#771 Added ToElement conversion for physics and atmosphere
  include/sdf/Atmosphere.hh
  include/sdf/Physics.hh
  src/Atmosphere.cc
  src/Atmosphere_TEST.cc
  src/Physics.cc
  src/Physics_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#772 Aded ToElement conversion for shapes
  include/sdf/Box.hh
  include/sdf/Capsule.hh
  include/sdf/Cylinder.hh
  include/sdf/Ellipsoid.hh
  include/sdf/Heightmap.hh
  include/sdf/Mesh.hh
  include/sdf/Plane.hh
  include/sdf/Sphere.hh
  src/Box.cc
  src/Box_TEST.cc
  src/Capsule.cc
  src/Capsule_TEST.cc
  src/Cylinder.cc
  src/Cylinder_TEST.cc
  src/Ellipsoid.cc
  src/Ellipsoid_TEST.cc
  src/Heightmap.cc
  src/Heightmap_TEST.cc
  src/Mesh.cc
  src/Mesh_TEST.cc
  src/Plane.cc
  src/Plane_TEST.cc
  src/Sphere.cc
  src/Sphere_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#774 Merge 6 -> 9
  Changelog.md
  include/sdf/CMakeLists.txt
  sdf/1.6/imu.sdf
  sdf/1.7/imu.sdf
Labels: 🏰 citadel, Gazebo 1️1️

#775 Material toelement
  include/sdf/Material.hh
  src/Material.cc
  src/Material_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#776 Added Geometry ToElement function
  include/sdf/Geometry.hh
  src/Geometry.cc
  src/Geometry_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#777 Added ToElement conversion for Collision, Surface, and Visual
  include/sdf/Collision.hh
  include/sdf/Surface.hh
  include/sdf/Visual.hh
  src/Collision.cc
  src/Collision_TEST.cc
  src/Surface.cc
  src/Visual.cc
  src/Visual_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#781 Added ToElement for ParticleEmitter and Link
  include/sdf/Link.hh
  include/sdf/ParticleEmitter.hh
  src/Link.cc
  src/Link_TEST.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#782 Model actor toelement functions
  include/sdf/Actor.hh
  include/sdf/Model.hh
  src/Actor.cc
  src/Actor_TEST.cc
  src/Model.cc
  src/Model_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#713 DOC: clarify behavior of //model/model/static
  sdf/1.5/model.sdf
  sdf/1.6/model.sdf
  sdf/1.7/model.sdf
  sdf/1.8/model.sdf
Labels: 🏢 edifice

#783 More to element
  include/sdf/Element.hh
  include/sdf/Gui.hh
  include/sdf/Scene.hh
  include/sdf/Sky.hh
  include/sdf/World.hh
  sdf/1.9/scene.sdf
  src/Actor.cc
  src/Actor_TEST.cc
  src/Collision.cc
  src/Element.cc
  src/Element_TEST.cc
  src/Geometry.cc
  src/Gui.cc
  src/Gui_TEST.cc
  src/Link.cc
  src/Link_TEST.cc
  src/Model.cc
  src/Model_TEST.cc
  src/ParticleEmitter.cc
  src/Scene.cc
  src/Scene_TEST.cc
  src/Sky.cc
  src/Sky_TEST.cc
  src/Visual.cc
  src/World.cc
  src/World_TEST.cc
  src/parser.cc
Labels: 🏯 fortress, 🌱 garden

#785 Support adding and clearing sensors from a joint
  include/sdf/Joint.hh
  src/Joint.cc
  src/Joint_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#786 Support URI in the Model DOM
  include/sdf/Model.hh
  src/Model.cc
  src/Model_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#788 Added plugin to SDF DOM
  include/sdf/CMakeLists.txt
  include/sdf/Gui.hh
  include/sdf/Plugin.hh
  sdf/1.9/plugin.sdf
  src/CMakeLists.txt
  src/Gui.cc
  src/Gui_TEST.cc
  src/Plugin.cc
  src/Plugin_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#789 Fix loading nested include with custom attributes
  src/parser.cc
  test/integration/model/model_with_custom_elements/model.config
  test/integration/model/model_with_custom_elements/model.sdf
  test/integration/sdf_custom.cc
Labels: 🏰 citadel, Gazebo 1️1️

#764 Refactor FrameSemantics.cc
  src/FrameSemantics.cc
  src/ign_TEST.cc
  test/integration/frame.cc
  test/integration/interface_api.cc
Labels: 🏯 fortress, 🌱 garden

#689 Support printing sdf poses in degrees and allow snapping to commonly used angles
  include/sdf/Element.hh
  include/sdf/Param.hh
  include/sdf/PrintConfig.hh
  src/CMakeLists.txt
  src/Element.cc
  src/Param.cc
  src/Plugin_TEST.cc
  src/PrintConfig.cc
  src/PrintConfig_TEST.cc
  src/cmd/cmdsdformat.rb.in
  src/ign.cc
  src/ign_TEST.cc
  src/parser.cc
  test/integration/default_elements.cc
  test/integration/include_custom_model_expected_output.sdf
  test/integration/include_custom_nested_model_expected_output.sdf
  test/integration/pose_1_9_sdf.cc
  test/integration/print_config.cc
  test/sdf/includes_rotations_in_degrees.sdf
  test/sdf/includes_rotations_in_quaternions.sdf
  test/sdf/includes_rotations_in_radians.sdf
  test/sdf/rotations_in_degrees.sdf
  test/sdf/rotations_in_degrees_high_snap_tolerance.sdf
  test/sdf/rotations_in_quaternions.sdf
  test/sdf/rotations_in_radians.sdf
  test/sdf/rotations_in_unnormalized_degrees.sdf
  test/sdf/rotations_in_unnormalized_radians.sdf
Labels: 🏯 fortress

#795 9 ➡️ 10
  src/parser.cc
  test/integration/model/model_with_custom_elements/model.config
  test/integration/model/model_with_custom_elements/model.sdf
  test/integration/sdf_custom.cc
Labels: 🔮 dome

#807 Merge part of 10 to 11
  test/integration/model/model_with_custom_elements/model.config
  test/integration/model/model_with_custom_elements/model.sdf
  test/integration/sdf_custom.cc
Labels: 🏢 edifice
