Repository gazebosim/sdformat, pull requests merged in 2021-06, with the labels that each got.

#578 Adding comment and modifications to element_tracing test regarding path sanitization
  test/integration/element_tracing.cc
Labels: 🏢 edifice

#582 Revert behavior of FilePath() for elements loaded from strings
  src/parser.cc
  src/parser_TEST.cc
  test/integration/element_tracing.cc
Labels: 🏢 edifice

#593 9 ➡️ 10
  include/sdf/Element.hh
  src/Element.cc
  src/Element_TEST.cc
  src/parser.cc
  test/integration/CMakeLists.txt
  test/integration/default_elements.cc
  test/sdf/empty_axis.sdf
  test/sdf/empty_road_sph_coords.sdf
  tools/code_check.sh
Labels: 🔮 dome

#594 11 ➡️ main
  src/parser.cc
  src/parser_TEST.cc
  src/parser_urdf.cc
  test/integration/element_tracing.cc
  test/integration/fixed_joint_reduction_collision_visual_extension.urdf
  test/integration/material.cc
  test/sdf/material_valid.urdf
Labels: 🏯 fortress

#564 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#575 Making PrintValues() and ToString() able to not print default elements
  include/sdf/Element.hh
  src/Element.cc
  src/Element_TEST.cc
  test/integration/default_elements.cc
  test/sdf/empty_road_sph_coords.sdf
Labels: 🏰 citadel

#598 10 to 11
  Changelog.md
  include/sdf/Element.hh
  include/sdf/ParticleEmitter.hh
  sdf/1.7/particle_emitter.sdf
  src/Element.cc
  src/Element_TEST.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  src/parser.cc
  test/integration/CMakeLists.txt
  test/integration/default_elements.cc
  test/integration/particle_emitter_dom.cc
  test/sdf/empty_axis.sdf
  test/sdf/empty_road_sph_coords.sdf
  test/sdf/world_complete.sdf
Labels: 🏢 edifice

#595 Add particle_scatter_ratio to SDF 1.6 spec
  sdf/1.6/particle_emitter.sdf
Labels: 🔮 dome

#599 🎈 11.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#413 Parameter passing prototype
  include/sdf/Error.hh
  src/CMakeLists.txt
  src/ParamPassing.cc
  src/ParamPassing.hh
  src/ParamPassing_TEST.cc
  src/XmlUtils.cc
  src/XmlUtils.hh
  src/parser.cc
  src/parser_private.hh
  test/integration/CMakeLists.txt
  test/integration/include_custom_model.sdf
  test/integration/include_custom_model_expected_output.sdf
  test/integration/include_custom_nested_model_expected_output.sdf
  test/integration/include_invalid_custom_model.sdf
  test/integration/include_model.sdf
  test/integration/model/nested_include/base/base.sdf
  test/integration/model/nested_include/base/model.config
  test/integration/model/nested_include/test_nested_include.sdf
  test/integration/model/nested_include/top_camera/model.config
  test/integration/model/nested_include/top_camera/top_camera.sdf
  test/integration/model/nested_include/top_model/model.config
  test/integration/model/nested_include/top_model/top_model.sdf
  test/integration/model/nested_include/wheel/model.config
  test/integration/model/nested_include/wheel/wheel.sdf
  test/integration/model/robot/model.config
  test/integration/model/robot/model.sdf
  test/integration/param_passing.cc
Labels: 🔮 dome

#604 11 ➡️ 12
  Changelog.md
  include/sdf/Element.hh
  include/sdf/ParticleEmitter.hh
  sdf/1.7/particle_emitter.sdf
  sdf/1.8/particle_emitter.sdf
  sdf/1.9/particle_emitter.sdf
  src/Element.cc
  src/Element_TEST.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  src/parser.cc
  test/integration/CMakeLists.txt
  test/integration/default_elements.cc
  test/integration/particle_emitter_dom.cc
  test/sdf/empty_axis.sdf
  test/sdf/empty_road_sph_coords.sdf
  test/sdf/world_complete.sdf
Labels: 🏯 fortress

#605 Fix ABI break
  include/sdf/Element.hh
Labels: 🏰 citadel

#608 Add triage, remove ticket templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/triage.yml
Labels: 🏢 edifice

#606 Fix ABI break on sdf11
  include/sdf/Element.hh
Labels: 🏢 edifice

#609 🎈 11.2.1
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🏢 edifice

#610 Fix segfault when checking for required elements in joint
  src/parser.cc
  src/parser_TEST.cc
Labels: 🏢 edifice

#612 9 ➡️ 10
  include/sdf/Element.hh
  src/Element.cc
  src/Element_TEST.cc
  test/integration/default_elements.cc
  test/sdf/empty_road_sph_coords.sdf
Labels: 🔮 dome

#613 11 ➡️ 12
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/triage.yml
  Changelog.md
  Migration.md
  include/sdf/Element.hh
  src/parser.cc
  src/parser_TEST.cc
Labels: 🏯 fortress
