Repository gazebosim/sdformat, pull requests merged in 2021-09, with the labels that each got.

#680 Upgrade cpplint and fix new errors
  include/sdf/Element.hh
  src/Converter_TEST.cc
  src/Error.cc
  src/FrameSemantics.cc
  src/Joint.cc
  src/Light.cc
  src/Link.cc
  src/Model.cc
  src/Noise.cc
  src/Pbr.cc
  src/SDF.cc
  src/Scene.cc
  src/Utils.hh
  src/ign_TEST.cc
  src/parser.cc
  src/parser_urdf.cc
  src/parser_urdf_TEST.cc
  test/integration/audio.cc
  test/integration/cfm_damping_implicit_spring_damper.cc
  test/integration/converter.cc
  test/integration/disable_fixed_joint_reduction.cc
  test/integration/element_memory_leak.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/force_torque_sensor.cc
  test/integration/locale_fix.cc
  test/integration/provide_feedback.cc
  test/integration/schema_test.cc
  test/integration/sdf_custom.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_joint_parameters.cc
  tools/cpplint.py
Labels: 🏰 citadel, Gazebo 1️1️

#681 Refactor sdf::readXml
  src/parser.cc
Labels: 🏰 citadel, Gazebo 1️1️

#589 New pose proposal: support rotation in degrees (#252)
  include/sdf/Element.hh
  include/sdf/Param.hh
  sdf/1.9/pose.sdf
  src/Element.cc
  src/Element_TEST.cc
  src/Param.cc
  src/Param_TEST.cc
  src/parser.cc
  src/parser_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/include_custom_model_expected_output.sdf
  test/integration/include_custom_nested_model_expected_output.sdf
  test/integration/nested_model_with_frames_expected.sdf
  test/integration/pose_1_9_sdf.cc
  test/integration/two_level_nested_model_with_frames_expected.sdf
  test/sdf/pose_1_9.sdf
Labels: 🏯 fortress

#682 Add a codecheck make target
  CMakeLists.txt
  cmake/SearchForStuff.cmake
  include/sdf/Console.hh
  include/sdf/Exception.hh
  include/sdf/Param.hh
  include/sdf/parser_urdf.hh
  src/Error.cc
  src/SDF.cc
  src/ign.cc
  test/integration/locale_fix_cxx.cc
Labels: 🏰 citadel, needs upstream release, Gazebo 1️1️

#651 Add enable_orientation SDF element to imu
  include/sdf/Imu.hh
  sdf/1.6/imu.sdf
  sdf/1.7/imu.sdf
  src/Imu.cc
  src/Imu_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🔮 dome

#687 10 -> 11
  .gitignore
  Changelog.md
  include/sdf/CMakeLists.txt
  include/sdf/Imu.hh
  include/sdf/NavSat.hh
  include/sdf/Sensor.hh
  sdf/1.6/imu.sdf
  sdf/1.7/imu.sdf
  sdf/1.7/navsat.sdf
  sdf/1.7/sensor.sdf
  sdf/1.8/imu.sdf
  sdf/1.8/navsat.sdf
  sdf/1.8/sensor.sdf
  src/CMakeLists.txt
  src/Imu.cc
  src/Imu_TEST.cc
  src/NavSat.cc
  src/NavSat_TEST.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏢 edifice

#684 Parse URDF continuous joint effort/velocity limits
  src/parser_urdf.cc
  test/integration/urdf_joint_parameters.cc
  test/integration/urdf_joint_parameters.urdf
Labels: 🏰 citadel, Gazebo 1️1️

#688 9 ➡️ 10
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  cmake/SearchForStuff.cmake
  include/sdf/Console.hh
  include/sdf/Element.hh
  include/sdf/Exception.hh
  include/sdf/Param.hh
  include/sdf/ParticleEmitter.hh
  sdf/1.5/model.sdf
  sdf/1.5/world.sdf
  sdf/1.6/model.sdf
  sdf/1.6/world.sdf
  sdf/1.7/model.sdf
  sdf/1.7/world.sdf
  src/Converter_TEST.cc
  src/Error.cc
  src/FrameSemantics.cc
  src/Joint.cc
  src/Light.cc
  src/Link.cc
  src/Model.cc
  src/Noise.cc
  src/Param.cc
  src/ParamPassing.cc
  src/Pbr.cc
  src/SDF.cc
  src/SDFExtension.hh
  src/Scene.cc
  src/Utils.cc
  src/Utils.hh
  src/ign.cc
  src/ign_TEST.cc
  src/parser.cc
  src/parser_TEST.cc
  src/parser_urdf.cc
  test/integration/cfm_damping_implicit_spring_damper.cc
  test/integration/disable_fixed_joint_reduction.cc
  test/integration/element_memory_leak.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/force_torque_sensor.cc
  test/integration/locale_fix.cc
  test/integration/locale_fix_cxx.cc
  test/integration/provide_feedback.cc
  test/integration/schema_test.cc
  test/integration/sdf_custom.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_joint_parameters.cc
  test/integration/urdf_joint_parameters.urdf
  tools/cpplint.py
Labels: 🔮 dome

#691 Bump to 9.6.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#692 10 ➡️ 11
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  cmake/SearchForStuff.cmake
  include/sdf/Console.hh
  include/sdf/Element.hh
  include/sdf/Exception.hh
  include/sdf/Model.hh
  include/sdf/Param.hh
  include/sdf/ParticleEmitter.hh
  include/sdf/World.hh
  src/Converter_TEST.cc
  src/Error.cc
  src/FrameSemantics.cc
  src/Joint.cc
  src/Light.cc
  src/Link.cc
  src/Model.cc
  src/Noise.cc
  src/Param.cc
  src/ParamPassing.cc
  src/Pbr.cc
  src/SDF.cc
  src/SDFExtension.hh
  src/Scene.cc
  src/Utils.cc
  src/ign.cc
  src/ign_TEST.cc
  src/parser.cc
  src/parser_TEST.cc
  src/parser_urdf.cc
  test/integration/cfm_damping_implicit_spring_damper.cc
  test/integration/disable_fixed_joint_reduction.cc
  test/integration/element_memory_leak.cc
  test/integration/element_tracing.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/force_torque_sensor.cc
  test/integration/interface_api.cc
  test/integration/locale_fix.cc
  test/integration/locale_fix_cxx.cc
  test/integration/nested_model.cc
  test/integration/provide_feedback.cc
  test/integration/schema_test.cc
  test/integration/sdf_custom.cc
  test/integration/toml_parser.hh
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_joint_parameters.cc
  test/integration/urdf_joint_parameters.urdf
  tools/cpplint.py
Labels: 🏢 edifice

#694 🎈 10.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome, beta

#695 Fix world-complete.sdf and add particle_scatter_ratio to v1.8
  sdf/1.8/particle_emitter.sdf
  test/sdf/world_complete.sdf
Labels: 🏢 edifice

#697 Fix/include pose degrees
  src/parser.cc
  test/integration/pose_1_9_sdf.cc
  test/sdf/include_pose_1_9.sdf
Labels: 🏯 fortress

#685 🌐 Parse spherical coordinates
  include/sdf/World.hh
  sdf/1.9/spherical_coordinates.sdf
  src/World.cc
  src/World_TEST.cc
  test/integration/world_dom.cc
  test/sdf/world_complete.sdf
Labels: beta, 🏯 fortress

#699 🎈 11.3.0
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏢 edifice

#666 DOC: clarify //pose/@relative_to
  sdf/1.7/frame.sdf
  sdf/1.7/model.sdf
  sdf/1.7/pose.sdf
  sdf/1.8/frame.sdf
  sdf/1.8/model.sdf
  sdf/1.8/pose.sdf
Labels: 🏢 edifice

#698 Fix documentation on Euler angle convention
  sdf/1.9/pose.sdf
Labels: documentation, beta, 🏯 fortress

#702 DOC: remove duplicate link
  sdf/1.7/pose.sdf
  sdf/1.8/pose.sdf
Labels: 🏢 edifice

#659 Support merge-include of nested models
  doc/sdf.in
  include/sdf/Error.hh
  include/sdf/InterfaceElements.hh
  include/sdf/Model.hh
  include/sdf/World.hh
  sdf/1.9/model.sdf
  src/CMakeLists.txt
  src/Error.cc
  src/Error_TEST.cc
  src/FrameSemantics.cc
  src/InterfaceElements.cc
  src/InterfaceElements_TEST.cc
  src/Utils.cc
  src/parser.cc
  test/integration/includes.cc
  test/integration/interface_api.cc
  test/integration/merge_include_model.sdf
  test/integration/model/merge_robot/model.config
  test/integration/model/merge_robot/model.sdf
  test/sdf/invalid_xml_syntax.sdf
  test/sdf/model_invalid_frame_only.sdf
Labels: beta, 🏯 fortress

#690 Support quaternions representation for poses
  include/sdf/Param.hh
  sdf/1.9/inertial.sdf
  sdf/1.9/pose.sdf
  src/Element.cc
  src/Param.cc
  src/Param_TEST.cc
  src/parser.cc
  test/integration/default_elements.cc
  test/integration/include_custom_model_expected_output.sdf
  test/integration/include_custom_nested_model_expected_output.sdf
  test/integration/nested_model_with_frames_expected.sdf
  test/integration/pose_1_9_sdf.cc
  test/integration/two_level_nested_model_with_frames_expected.sdf
  test/sdf/empty_road_sph_coords.sdf
  test/sdf/include_pose_1_9.sdf
  test/sdf/pose_1_9.sdf
Labels: beta, 🏯 fortress

#706 Merge 11 -> 12
  Changelog.md
  sdf/1.7/frame.sdf
  sdf/1.7/model.sdf
  sdf/1.7/pose.sdf
  sdf/1.8/frame.sdf
  sdf/1.8/model.sdf
  sdf/1.8/pose.sdf
  sdf/1.9/frame.sdf
  sdf/1.9/model.sdf
  sdf/1.9/pose.sdf
  test/sdf/world_complete.sdf
Labels: beta, 🏯 fortress

#669 Added Force Torque Noise functions + Unit tests
  include/sdf/ForceTorque.hh
  sdf/1.9/forcetorque.sdf
  src/ForceTorque.cc
  src/ForceTorque_TEST.cc
  test/integration/joint_dom.cc
  test/sdf/joint_sensors.sdf
Labels: beta, 🏯 fortress

#709 Prepeare for 12.0.0~pre2
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🏯 fortress

#711 Prefix merged frames with an underscore
  src/parser.cc
  test/integration/includes.cc
Labels: bug, beta, 🏯 fortress

#715 DOC: don't mention elements that can't be included
  sdf/1.8/model.sdf
Labels: 🏢 edifice

#717 Do not automatically remove //axis/initial_position
  sdf/1.9/1_8.convert
  src/parser_TEST.cc
  test/integration/joint_axis_dom.cc
Labels: bug, beta, 🏯 fortress

#714 Added macos install instructions to README.md
  README.md
Labels: documentation, beta, macOS, 🏯 fortress

#720 Remove empty //inertial/pose/@relative_to during 1_7->1.8 conversion
  sdf/1.8/1_7.convert
  src/Converter.cc
  src/Converter.hh
  src/Converter_TEST.cc
  test/sdf/model_frame_relative_to_joint.sdf
Labels: 🏢 edifice

#723 Merge 11 ➡️ main
  sdf/1.8/1_7.convert
  sdf/1.8/model.sdf
  sdf/1.9/model.sdf
  src/Converter.cc
  src/Converter.hh
  src/Converter_TEST.cc
  test/sdf/model_frame_relative_to_joint.sdf
Labels: bug, beta, 🏯 fortress

#721 Make exception for plugins when checking for name uniqueness
  include/sdf/Element.hh
  src/Element.cc
  src/Model.cc
  src/World.cc
  src/ign_TEST.cc
  src/parser.cc
  test/integration/model_dom.cc
  test/integration/world_dom.cc
  test/sdf/model_duplicate_plugins.sdf
  test/sdf/world_duplicate_plugins.sdf
Labels: bug, beta, 🏯 fortress

#724 🎈 12.0.0
  CMakeLists.txt
  Changelog.md
  README.md
Labels: beta, 🏯 fortress
