Repository gazebosim/sdformat, pull requests merged in 2021-04, with the labels that each got.

#528 Particle emitter
  include/sdf/CMakeLists.txt
  include/sdf/Link.hh
  include/sdf/ParticleEmitter.hh
  include/sdf/SemanticPose.hh
  sdf/1.6/link.sdf
  sdf/1.6/particle_emitter.sdf
  sdf/1.7/link.sdf
  sdf/1.7/particle_emitter.sdf
  src/CMakeLists.txt
  src/Link.cc
  src/Link_TEST.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  src/Visual.cc
  test/integration/CMakeLists.txt
  test/integration/particle_emitter_dom.cc
  test/sdf/world_complete.sdf
Labels: 🏢 edifice

#525 Fixed application of <sensor><pose> tags in lumped linkes during URDF conversion
  Migration.md
  src/parser_urdf.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🔮 dome

#534 10.4.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#539 10 to 11 20210412
  Changelog.md
  Migration.md
  include/sdf/CMakeLists.txt
  include/sdf/Link.hh
  include/sdf/ParticleEmitter.hh
  include/sdf/SemanticPose.hh
  sdf/1.6/link.sdf
  sdf/1.6/particle_emitter.sdf
  sdf/1.7/link.sdf
  sdf/1.7/particle_emitter.sdf
  sdf/1.8/link.sdf
  sdf/1.8/particle_emitter.sdf
  src/CMakeLists.txt
  src/Link.cc
  src/Link_TEST.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  src/parser_urdf.cc
  test/integration/CMakeLists.txt
  test/integration/particle_emitter_dom.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
  test/sdf/world_complete.sdf
Labels: 🏢 edifice

#537 Fixed file path in errors when parsing sdf or urdf from string
  include/sdf/Types.hh
  src/Element.cc
  src/parser.cc
  src/parser_TEST.cc
Labels: 🏢 edifice

#543 Add an EnforcementPolicy for deprecated elements
  Migration.md
  include/sdf/Console.hh
  include/sdf/Element.hh
  include/sdf/ParserConfig.hh
  src/Console.cc
  src/ParserConfig.cc
  src/parser.cc
  test/integration/deprecated_specs.cc
  test/test_utils.hh
Labels: 🏢 edifice

#555 Methods for removing attributes from an element
  include/sdf/Element.hh
  src/Element.cc
  src/Element_TEST.cc
Labels: 🏰 citadel

#557 9 ➡️ 10
  include/sdf/Element.hh
  sdf/1.4/surface.sdf
  sdf/1.5/surface.sdf
  sdf/1.6/surface.sdf
  sdf/1.7/surface.sdf
  src/Element.cc
  src/Element_TEST.cc
Labels: 🔮 dome

#549 Clean up use of PROJECT_SOURCE_PATH in tests
  src/FrameSemantics_TEST.cc
  src/ParserConfig_TEST.cc
  src/parser_TEST.cc
  test/integration/deprecated_specs.cc
  test/integration/interface_api.cc
  test/integration/joint_dom.cc
  test/integration/locale_fix.cc
  test/integration/model_dom.cc
  test/integration/nested_model.cc
  test/integration/nested_multiple_elements_error.cc
  test/integration/parser_config.cc
  test/integration/schema_test.cc
  test/integration/unknown.cc
  test/integration/visual_dom.cc
Labels: 🏢 edifice

#558 10 ➡️ 11
  include/sdf/Element.hh
  sdf/1.4/surface.sdf
  sdf/1.5/surface.sdf
  sdf/1.6/surface.sdf
  sdf/1.7/surface.sdf
  src/Element.cc
  src/Element_TEST.cc
Labels: 🏢 edifice

#560 🎈11.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#559 11 ➡️ main
  Changelog.md
  Migration.md
  include/sdf/CMakeLists.txt
  include/sdf/Console.hh
  include/sdf/Element.hh
  include/sdf/Link.hh
  include/sdf/ParserConfig.hh
  include/sdf/ParticleEmitter.hh
  include/sdf/SemanticPose.hh
  include/sdf/Types.hh
  sdf/1.4/surface.sdf
  sdf/1.5/surface.sdf
  sdf/1.6/link.sdf
  sdf/1.6/particle_emitter.sdf
  sdf/1.6/surface.sdf
  sdf/1.7/link.sdf
  sdf/1.7/particle_emitter.sdf
  sdf/1.7/surface.sdf
  sdf/1.8/link.sdf
  sdf/1.8/particle_emitter.sdf
  src/CMakeLists.txt
  src/Console.cc
  src/Element.cc
  src/Element_TEST.cc
  src/FrameSemantics_TEST.cc
  src/Link.cc
  src/Link_TEST.cc
  src/ParserConfig.cc
  src/ParserConfig_TEST.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  src/parser.cc
  src/parser_TEST.cc
  src/parser_urdf.cc
  test/integration/CMakeLists.txt
  test/integration/deprecated_specs.cc
  test/integration/interface_api.cc
  test/integration/joint_dom.cc
  test/integration/locale_fix.cc
  test/integration/model_dom.cc
  test/integration/nested_model.cc
  test/integration/nested_multiple_elements_error.cc
  test/integration/parser_config.cc
  test/integration/particle_emitter_dom.cc
  test/integration/schema_test.cc
  test/integration/unknown.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
  test/integration/visual_dom.cc
  test/sdf/world_complete.sdf
  test/test_utils.hh
Labels: 🏯 fortress
