Repository gazebosim/sdformat, pull requests merged in 2021-11, with the labels that each got.

#737 Support accessing mutable sensor types
  include/sdf/Sensor.hh
  src/Sensor.cc
  src/Sensor_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#739 Prepare for v9.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#740 Remove outdated deprecation note from parser_urdf.hh
  src/parser_urdf.hh
Labels: 🔮 dome

#686 Backport imu enable_orientation field to sdf6
  sdf/1.6/imu.sdf
Labels: Gazebo 9️

#738 6 ➡️ 9
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Changelog.md
  Migration.md
  bitbucket-pipelines.yml
  doc/header.html
  doc/mainpage.html
  src/parser.cc
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_plugin_frame_extension.urdf
  test/integration/frame.cc
  test/integration/model/box_with_submodel/model.config
  test/integration/model/box_with_submodel/model.sdf
  test/integration/model/nested_names_test/model.config
  test/integration/model/nested_names_test/submodel_test.sdf
  test/integration/nested_model.cc
Labels: 🏰 citadel, Gazebo 1️1️

#716 DOC: only allow one canonical_link attribute
  sdf/1.7/model.sdf
  sdf/1.8/model.sdf
Labels: 🏢 edifice

#743 Prepare for 12.1.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress, 🌱 garden

#745 Fix URDF fixed joint reduction of plugins
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_plugin_frame_extension.urdf
Labels: 🔮 dome

#750 Merge 9 -> 10
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Changelog.md
  Migration.md
  bitbucket-pipelines.yml
  doc/header.html
  doc/mainpage.html
  include/sdf/CMakeLists.txt
  include/sdf/Console.hh
  include/sdf/Element.hh
  include/sdf/ForceTorque.hh
  include/sdf/Joint.hh
  include/sdf/Sensor.hh
  sdf/1.4/sensor.sdf
  sdf/1.5/forcetorque.sdf
  sdf/1.5/sensor.sdf
  sdf/1.6/forcetorque.sdf
  sdf/1.6/sensor.sdf
  sdf/1.7/forcetorque.sdf
  sdf/1.7/sensor.sdf
  src/CMakeLists.txt
  src/Console.cc
  src/Element.cc
  src/ForceTorque.cc
  src/ForceTorque_TEST.cc
  src/Joint.cc
  src/Joint_TEST.cc
  src/Model.cc
  src/Sensor.cc
  src/World.cc
  src/ign_TEST.cc
  src/parser.cc
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/frame.cc
  test/integration/joint_dom.cc
  test/integration/model/box_with_submodel/model.config
  test/integration/model/box_with_submodel/model.sdf
  test/integration/model/nested_names_test/model.config
  test/integration/model/nested_names_test/submodel_test.sdf
  test/integration/model_dom.cc
  test/integration/nested_model.cc
  test/integration/world_dom.cc
  test/sdf/joint_sensors.sdf
  test/sdf/model_duplicate_plugins.sdf
  test/sdf/world_duplicate_plugins.sdf
  test/test_utils.hh
Labels: 🔮 dome

#753 Add function to convert Sensor DOM to sdf::ElementPtr
  include/sdf/AirPressure.hh
  include/sdf/Altimeter.hh
  include/sdf/Camera.hh
  include/sdf/ForceTorque.hh
  include/sdf/Imu.hh
  include/sdf/Lidar.hh
  include/sdf/Magnetometer.hh
  include/sdf/Noise.hh
  include/sdf/Sensor.hh
  src/AirPressure.cc
  src/Altimeter.cc
  src/Camera.cc
  src/Camera_TEST.cc
  src/ForceTorque.cc
  src/Imu.cc
  src/Lidar.cc
  src/Magnetometer.cc
  src/Noise.cc
  src/Sensor.cc
  test/integration/CMakeLists.txt
  test/integration/sdf_dom_conversion.cc
  test/sdf/sensors.sdf
Labels: 🏯 fortress, 🌱 garden

#752 Merge 10 -> 11
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Changelog.md
  Migration.md
  bitbucket-pipelines.yml
  doc/header.html
  doc/mainpage.html
  include/sdf/Element.hh
  include/sdf/ForceTorque.hh
  sdf/1.7/forcetorque.sdf
  sdf/1.8/forcetorque.sdf
  src/Element.cc
  src/ForceTorque.cc
  src/ForceTorque_TEST.cc
  src/Model.cc
  src/World.cc
  src/ign_TEST.cc
  src/parser.cc
  src/parser_urdf.cc
  src/parser_urdf.hh
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_plugin_frame_extension.urdf
  test/integration/frame.cc
  test/integration/joint_dom.cc
  test/integration/model/box_with_submodel/model.config
  test/integration/model/box_with_submodel/model.sdf
  test/integration/model_dom.cc
  test/integration/world_dom.cc
  test/sdf/joint_sensors.sdf
  test/sdf/model_duplicate_plugins.sdf
  test/sdf/world_duplicate_plugins.sdf
Labels: 🏢 edifice

#744 Support wide angle camera
  include/sdf/Sensor.hh
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏯 fortress, 🌱 garden

#757 Update Sensor DOM to Element functions and add tests
  include/sdf/AirPressure.hh
  include/sdf/Altimeter.hh
  include/sdf/Camera.hh
  include/sdf/ForceTorque.hh
  include/sdf/Imu.hh
  include/sdf/Lidar.hh
  include/sdf/Magnetometer.hh
  include/sdf/Noise.hh
  include/sdf/Sensor.hh
  src/AirPressure.cc
  src/AirPressure_TEST.cc
  src/Altimeter.cc
  src/Altimeter_TEST.cc
  src/Camera.cc
  src/Camera_TEST.cc
  src/ForceTorque.cc
  src/ForceTorque_TEST.cc
  src/Imu.cc
  src/Imu_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/Magnetometer.cc
  src/Magnetometer_TEST.cc
  src/Noise.cc
  src/Noise_TEST.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/sdf_dom_conversion.cc
Labels: 🏯 fortress, 🌱 garden

#756 Merge 11 -> 12
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Changelog.md
  Migration.md
  bitbucket-pipelines.yml
  doc/header.html
  doc/mainpage.html
  include/sdf/parser.hh
  sdf/1.7/forcetorque.sdf
  sdf/1.7/model.sdf
  sdf/1.8/forcetorque.sdf
  sdf/1.8/model.sdf
  sdf/1.9/forcetorque.sdf
  sdf/1.9/model.sdf
  src/Converter.cc
  src/FrameSemantics.cc
  src/Joint.cc
  src/Root.cc
  src/World.cc
  src/ign_TEST.cc
  src/parser.cc
  src/parser_TEST.cc
  src/parser_urdf.cc
  src/parser_urdf.hh
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_plugin_frame_extension.urdf
  test/integration/frame.cc
  test/integration/interface_api.cc
  test/integration/joint_dom.cc
  test/integration/model/box_with_submodel/model.config
  test/integration/model/box_with_submodel/model.sdf
  test/integration/nested_model.cc
  test/integration/unknown.cc
  test/sdf/joint_axis_infinite_limits.sdf
  test/sdf/joint_axis_xyz_normalization.sdf
Labels: 🏯 fortress, 🌱 garden

#760 Prepare for 12.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress, 🌱 garden

#761 Backport cmake/test fixes to sdf6
  Changelog.md
  cmake/SearchForStuff.cmake
  include/sdf/CMakeLists.txt
  test/integration/element_memory_leak.cc
Labels: Gazebo 9️
