Repository gazebosim/sdformat, pull requests merged in 2022-08, with the labels that each got.

#1106 Add option to skip python bindings
  CMakeLists.txt
Labels: bug, 🌱 garden

#1108 Remove unused macros from config.hh
  include/sdf/config.hh.in
Labels: bug, 🌱 garden

#1095 Element: add sdf::Errors output to API methods
  include/sdf/Element.hh
  include/sdf/Error.hh
  include/sdf/Param.hh
  src/Element.cc
  src/Param.cc
  src/Utils.cc
  src/Utils.hh
  src/gz_TEST.cc
  src/parser_TEST.cc
  test/integration/error_output.cc
Labels: enhancement

#1112 1.10/joint.sdf: better default limit values
  Migration.md
  python/test/pyJointAxis_TEST.py
  sdf/1.10/joint.sdf
  src/JointAxis.cc
  src/JointAxis_TEST.cc
  test/integration/joint_axis_dom.cc
Labels: bug, 🌱 garden

#1113 sdf/1.10: remove unused spec files
  Migration.md
  sdf/1.10/collision_engine.sdf
  sdf/1.10/urdf.sdf
Labels: 🌱 garden

#1114 urdf: fix sensor/light pose for links lumped by fixed joints
  Migration.md
  src/parser_urdf.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🏰 citadel, Gazebo 1️1️

#1119 Merge sdf9 ➡️ sdf12
  Migration.md
  src/parser_urdf.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🏯 fortress

#1120 Merge sdf12 ➡️ sdf13
  Migration.md
  src/parser_urdf.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🌱 garden

#1098 PrintConfig: add sdf::Errors output to API methods
  include/sdf/PrintConfig.hh
  src/PrintConfig.cc
  test/integration/error_output.cc
Labels: enhancement

#1109 Add camera optical_frame_id element
  include/sdf/Camera.hh
  sdf/1.7/camera.sdf
  sdf/1.8/camera.sdf
  sdf/1.9/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
Labels: 🏯 fortress

#1088 sdf/camera.sdf: fields for projection matrix
  Migration.md
  include/sdf/Camera.hh
  sdf/1.7/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: enhancement, 🏰 citadel, Gazebo 1️1️
