Repository gazebosim/sdformat, pull requests merged in 2022-04, with the labels that each got.

#925 SDF to USD: Added collision tag
  usd/src/CMakeLists.txt
  usd/src/cmd/CMakeLists.txt
  usd/src/sdf_parser/Collision.cc
  usd/src/sdf_parser/Collision.hh
  usd/src/sdf_parser/Geometry.cc
  usd/src/sdf_parser/Geometry_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/Link.cc
Labels: 🏯 fortress, usd

#911 Added convenience constructor to plugin
  include/sdf/Plugin.hh
  src/CMakeLists.txt
  src/Plugin.cc
  src/Plugin_TEST.cc
  src/Utils.cc
  src/Utils.hh
  src/parser.cc
Labels: 🏯 fortress

#922 [fortress] Forward Port #909
  include/sdf/Camera.hh
  sdf/1.7/camera.sdf
  sdf/1.8/camera.sdf
  sdf/1.9/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
Labels: 🏯 fortress

#932 Python: Added basic structure
  .github/ci/packages.apt
  CMakeLists.txt
  examples/python/README.md
  examples/python/python_sdformat.py
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
Labels: scripting, 🌱 garden, mujoco

#876 USD -> SDF: Added model tag
  test/usd/upAxisZ.usda
  usd/include/sdf/usd/UsdError.hh
  usd/src/usd_parser/USDData.cc
  usd/src/usd_parser/USDData_TEST.cc
  usd/src/usd_parser/USDLight_TEST.cc
  usd/src/usd_parser/USDPhysics_TEST.cc
  usd/src/usd_parser/USDStage_TEST.cc
  usd/src/usd_parser/USDTransforms_TEST.cc
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: usd

#953 Added __copy__ and __deepcopy__ to Error and ParserConfig
  python/src/sdf/pyError.cc
  python/src/sdf/pyParserConfig.cc
  python/test/pyError_TEST.py
  python/test/pyParserConfig_TEST.py
Labels: scripting, 🌱 garden, mujoco

#936 Added ``--inertial-stats`` option to ``ign sdf``
  src/cmd/cmdsdformat.rb.in
  src/ign.cc
  src/ign_TEST.cc
  test/sdf/inertial_stats.sdf
Labels: 🏯 fortress

#902 USD to SDF: Added links
  test/usd/upAxisZ.usda
  usd/src/CMakeLists.txt
  usd/src/cmd/usd2sdf.cc
  usd/src/usd_parser/USDLinks.cc
  usd/src/usd_parser/USDLinks.hh
  usd/src/usd_parser/USDLinks_TEST.cc
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: usd

#959 Backport #487 to sdf9: support L16 pixel format
  sdf/1.7/camera.sdf
  src/Camera.cc
Labels: 🏰 citadel, Gazebo 1️1️

#957 Fixes MacOS Python tests
  .github/workflows/macos.yml
Labels: scripting, 🌱 garden

#897 USD to SDF: Added visuals
  test/usd/upAxisZ.usda
  usd/include/sdf/usd/UsdError.hh
  usd/src/CMakeLists.txt
  usd/src/usd_parser/USDLinks.cc
  usd/src/usd_parser/USDLinks.hh
  usd/src/usd_parser/USDLinks_TEST.cc
  usd/src/usd_parser/USDMaterial.cc
  usd/src/usd_parser/USDStage_TEST.cc
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/polygon_helper.cc
  usd/src/usd_parser/polygon_helper.hh
Labels: usd

#958 Backport ``ign sdf --inertial-stats``
  src/cmd/cmdsdformat.rb.in
  src/ign.cc
  src/ign_TEST.cc
  test/sdf/inertial_stats.sdf
Labels: 🏯 fortress

#965 Merge 9 -> 12
  src/ign.cc
  src/ign_TEST.cc
Labels: 🏯 fortress

#898 USD to SDF: Added Collisions
  usd/src/usd_parser/USDLinks.cc
  usd/src/usd_parser/USDLinks_TEST.cc
Labels: usd

#872 Changed default floating point precision to max
  include/sdf/Param.hh
  include/sdf/PrintConfig.hh
  src/Param.cc
  src/PrintConfig.cc
  src/PrintConfig_TEST.cc
  src/cmd/cmdsdformat.rb.in
  src/ign.cc
  src/ign_TEST.cc
  test/integration/default_elements.cc
  test/integration/model/test_model_with_frames_no_rotations/model.config
  test/integration/model/test_model_with_frames_no_rotations/model.sdf
  test/integration/model/test_nested_model_with_frames/model.sdf
  test/integration/nested_model.cc
  test/integration/nested_model_with_frames_expected.sdf
  test/integration/pose_1_9_sdf.cc
  test/integration/print_config.cc
  test/integration/two_level_nested_model_with_frames_expected.sdf
Labels: 🌱 garden

#899 USD to SDF: Added Joints
  test/usd/double_pendulum.usda
  usd/src/CMakeLists.txt
  usd/src/usd_parser/USDJoints.cc
  usd/src/usd_parser/USDJoints.hh
  usd/src/usd_parser/USDJoints_TEST.cc
  usd/src/usd_parser/USDWorld.cc
Labels: usd

#974 Bumps in garden : sdformat13
  .github/ci/packages.apt
  CMakeLists.txt
  examples/usdConverter/README.md
Labels: 🌱 garden

#955 Added Friction and ODE classes
  include/sdf/Surface.hh
  src/Surface.cc
  src/Surface_TEST.cc
  test/integration/surface_dom.cc
  test/sdf/shapes.sdf
Labels: 🏯 fortress, usd

#976 SDF to USD: check and fix if path is valid
  usd/src/UsdUtils.hh
  usd/src/UsdUtils_TEST.cc
  usd/src/cmd/sdf2usd.cc
  usd/src/sdf_parser/Geometry.cc
  usd/src/sdf_parser/Link.cc
  usd/src/sdf_parser/Model.cc
  usd/src/sdf_parser/Visual.cc
  usd/src/sdf_parser/World.cc
Labels: 🏯 fortress, usd

#900 USD to SDF: Added Sensors
  test/usd/sensors.usda
  usd/src/CMakeLists.txt
  usd/src/usd_parser/USDSensors.cc
  usd/src/usd_parser/USDSensors.hh
  usd/src/usd_parser/USDSensors_TEST.cc
  usd/src/usd_parser/USDWorld.cc
Labels: usd

#940 Added Surface Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pySurface.cc
  python/src/sdf/pySurface.hh
  python/test/pySurface_TEST.py
Labels: scripting, 🌱 garden, mujoco

#978 Use ign-utils instead of ign-cmake utilities
  src/CMakeLists.txt
  src/ign_TEST.cc
  usd/src/CMakeLists.txt
  usd/src/sdf_parser/sdf2usd_TEST.cc
  usd/src/usd_parser/USDData_TEST.cc
  usd/src/usd_parser/USDStage_TEST.cc
  usd/src/usd_parser/USDTransforms_TEST.cc
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: 🏯 fortress

#980 Bumps in garden : sdformat13
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🌱 garden

#944 Added Capsule Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyCapsule.cc
  python/src/sdf/pyCapsule.hh
  python/test/pyCapsule_TEST.py
Labels: needs upstream release, scripting, 🌱 garden, mujoco

#948 Added Material Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyMaterial.cc
  python/src/sdf/pyMaterial.hh
  python/test/pyMaterial_TEST.py
Labels: scripting, 🌱 garden, mujoco

#969 Added Noise Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyNoise.cc
  python/src/sdf/pyNoise.hh
  python/test/pyNoise_TEST.py
Labels: scripting, 🌱 garden, mujoco

#903 USD to SDF: Added Lights attached to models
  test/usd/upAxisZ.usda
  usd/src/usd_parser/USDStage_TEST.cc
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: usd

#951 Added SemanticPose Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pySemanticPose.cc
  python/src/sdf/pySemanticPose.hh
  python/test/pyBox_TEST.py
  python/test/pySemanticPose_TEST.py
Labels: scripting, 🌱 garden, mujoco

#904 USD to SDF: Added diff drive plugin
  usd/include/sdf/usd/usd_parser/Parser.hh
  usd/src/cmd/usd2sdf.cc
  usd/src/usd_parser/Parser.cc
  usd/src/usd_parser/USD2SDF.cc
  usd/src/usd_parser/USD2SDF.hh
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/USDWorld.hh
Labels: usd

#947 Added Geometry Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyGeometry.cc
  python/src/sdf/pyGeometry.hh
  python/test/pyGeometry_TEST.py
Labels: needs upstream release, scripting, 🌱 garden, mujoco

#949 Added Collision Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyCollision.cc
  python/src/sdf/pyCollision.hh
  python/test/pyCollision_TEST.py
Labels: scripting, 🌱 garden, mujoco

#991 USD to SDF: some fixes
  test/usd/upAxisZ.usda
  usd/src/usd_parser/USDLinks.cc
  usd/src/usd_parser/USDWorld.cc
Labels: 🏯 fortress, usd

#912 Added equality operators to Plugin
  include/sdf/Plugin.hh
  src/Plugin.cc
  src/Plugin_TEST.cc
Labels: 🏯 fortress

#960 Added JointAxis Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyJointAxis.cc
  python/src/sdf/pyJointAxis.hh
  python/test/pyJointAxis_TEST.py
Labels: scripting, 🌱 garden, mujoco

#985 Added <shininess> to <material>
  include/sdf/Material.hh
  sdf/1.7/material.sdf
  src/Material.cc
  src/Material_TEST.cc
Labels: 🏰 citadel, Gazebo 1️1️

#950 Added Visual Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyVisual.cc
  python/src/sdf/pyVisual.hh
  python/test/pyVisual_TEST.py
Labels: scripting, 🌱 garden, mujoco

#952 Added Link Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyLink.cc
  python/src/sdf/pyLink.hh
  python/test/pyLink_TEST.py
Labels: scripting, 🌱 garden, mujoco

#961 Added Joint Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyJoint.cc
  python/src/sdf/pyJoint.hh
  python/test/pyJoint_TEST.py
Labels: scripting, 🌱 garden, mujoco

#962 Added Frame Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyFrame.cc
  python/src/sdf/pyFrame.hh
  python/test/pyFrame_TEST.py
Labels: scripting, 🌱 garden, mujoco

#963 Added Model Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyModel.cc
  python/src/sdf/pyModel.hh
  python/test/pyModel_TEST.py
Labels: scripting, 🌱 garden, mujoco

#1000 Polyline geometry DOM
  include/sdf/CMakeLists.txt
  include/sdf/Cylinder.hh
  include/sdf/Geometry.hh
  include/sdf/Polyline.hh
  src/CMakeLists.txt
  src/Geometry.cc
  src/Geometry_TEST.cc
  src/Polyline.cc
  src/Polyline_TEST.cc
  src/Visual_TEST.cc
  test/integration/geometry_dom.cc
  test/sdf/shapes.sdf
Labels: 🏰 citadel, Gazebo 1️1️, MBARI buoy

#964 Added World Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyWorld.cc
  python/src/sdf/pyWorld.hh
  python/test/pyWorld_TEST.py
Labels: scripting, 🌱 garden, mujoco

#1001 Added SemanticPose Python test
  python/test/pySemanticPose_TEST.py
Labels: scripting, 🌱 garden, mujoco

#1005 Prepare for 9.8.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️
