Repository gazebosim/sdformat, pull requests merged in 2022-02, with the labels that each got.

#768 Add support for merge-include in the Interface API
  include/sdf/Error.hh
  include/sdf/InterfaceElements.hh
  include/sdf/InterfaceModel.hh
  include/sdf/Model.hh
  src/CMakeLists.txt
  src/FrameSemantics.cc
  src/InterfaceElements.cc
  src/InterfaceModel.cc
  src/Model.cc
  src/Utils.cc
  src/Utils.hh
  src/World.cc
  src/parser.cc
  test/integration/interface_api.cc
  test/integration/model/joint_child_model_frame.toml
  test/sdf/merge_include_with_interface_api_frame_semantics.sdf
  test/sdf/merge_include_with_interface_api_reposture.sdf
Labels: 🏯 fortress, 🌱 garden

#849 Use USD component visibility macro
  usd/include/sdf/usd/sdf_parser/Light.hh
  usd/include/sdf/usd/sdf_parser/Utils.hh
  usd/include/sdf/usd/sdf_parser/World.hh
Labels: 🏯 fortress

#836 Add USDError class
  usd/include/sdf/usd/UsdError.hh
  usd/include/sdf/usd/sdf_parser/Light.hh
  usd/include/sdf/usd/sdf_parser/World.hh
  usd/src/CMakeLists.txt
  usd/src/UsdError.cc
  usd/src/UsdError_TEST.cc
  usd/src/sdf_parser/Light.cc
  usd/src/sdf_parser/World.cc
Labels: 🏯 fortress

#838 Added non-const accessors for Link child objects
  include/sdf/Link.hh
  src/Link.cc
  src/Link_TEST.cc
Labels: 🏯 fortress

#850 Hide the USD component's Util.hh file from public API
  usd/src/CMakeLists.txt
  usd/src/UsdTestUtils.hh
  usd/src/UsdUtils.hh
  usd/src/UsdUtils_TEST.cc
  usd/src/sdf_parser/Light.cc
  usd/src/sdf_parser/Light_Sdf2Usd_TEST.cc
Labels: 🏯 fortress

#841 Added Root mutable accessors, and Root::Clone function
  include/sdf/Root.hh
  src/FrameSemantics.cc
  src/Root.cc
  src/Root_TEST.cc
  test/integration/root_dom.cc
Labels: 🏯 fortress

#851 Added to light if the light is on or off
  include/sdf/Light.hh
  sdf/1.8/light.sdf
  src/Light.cc
  src/Light_TEST.cc
Labels: 🏢 edifice

#839 Added non-const accessors for Model child objects
  include/sdf/Model.hh
  src/Model.cc
  src/Model_TEST.cc
Labels: 🏯 fortress

#840 Added non-const mutable accessors for world child objects
  include/sdf/World.hh
  src/World.cc
  src/World_TEST.cc
Labels: 🏯 fortress

#847 Updated tests for ign-math's ostream fix
  test/integration/default_elements.cc
  test/integration/include_custom_model_expected_output.sdf
  test/integration/include_custom_nested_model_expected_output.sdf
Labels: 🌱 garden

#857 Remove USD visibility macro from internal APIs
  usd/src/UsdUtils.hh
Labels: 🏯 fortress, usd

#854 Switch to utils version of env functions
  src/Console.cc
  src/Console_TEST.cc
  src/Filesystem_TEST.cc
  src/SDF.cc
  src/SDF_TEST.cc
  src/ign_TEST.cc
  src/parser_TEST.cc
  test/env.hh
  test/test_config.h.in
Labels: 🌱 garden

#855 Fix joint parent/child frame existence checks to include interface elements
  include/sdf/Model.hh
  src/Model.cc
  src/parser.cc
  test/integration/interface_api.cc
  test/integration/model_dom.cc
Labels: 🏢 edifice

#859 11 ➡️ 12
  include/sdf/Light.hh
  include/sdf/Model.hh
  sdf/1.8/light.sdf
  sdf/1.9/light.sdf
  src/Light.cc
  src/Light_TEST.cc
  src/Model.cc
  src/parser.cc
  test/integration/interface_api.cc
  test/integration/model_dom.cc
Labels: 🏯 fortress

#853 Fix bug where //include/pose was ignored when using the Interface API
  src/FrameSemantics.cc
  test/integration/interface_api.cc
  test/integration/model/double_pendulum.toml
Labels: 🏯 fortress

#837 sdf -> usd converter: add joints
  test/integration/joint_dom.cc
  test/sdf/ball_prismatic_joint.sdf
  test/sdf/double_pendulum.sdf
  test/sdf/joint_parent_world.sdf
  usd/include/sdf/usd/sdf_parser/Joint.hh
  usd/src/CMakeLists.txt
  usd/src/sdf_parser/Joint.cc
  usd/src/sdf_parser/Joint_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/Model.cc
Labels: usd

#861 Coverage build on focal
  .github/workflows/ci.yml
Labels: 🏯 fortress

#830 sdf -> usd: Added sensor
  test/sdf/usd_sensors.sdf
  usd/include/sdf/usd/sdf_parser/Sensor.hh
  usd/src/CMakeLists.txt
  usd/src/sdf_parser/Link.cc
  usd/src/sdf_parser/Sensor.cc
  usd/src/sdf_parser/Sensors_Sdf2Usd_TEST.cc
Labels: usd
