Repository gazebosim/sdformat, pull requests merged in 2022-07, with the labels that each got.

#1065 Document major and minor SDFormat version numbers
  sdf/1.3/root.sdf
  sdf/1.4/root.sdf
  sdf/1.5/root.sdf
  sdf/1.6/root.sdf
  sdf/1.7/root.sdf
  sdf/1.8/root.sdf
  sdf/1.9/root.sdf
Labels: documentation, 🌱 garden

#1069 Backport to fortress: document SDFormat version numbers
  sdf/1.3/root.sdf
  sdf/1.4/root.sdf
  sdf/1.5/root.sdf
  sdf/1.6/root.sdf
  sdf/1.7/root.sdf
  sdf/1.8/root.sdf
  sdf/1.9/root.sdf
Labels: 🏯 fortress

#1048 ign -> gz Shared Lib Migration : sdformat
  test/integration/model/pr2.sdf
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: 🌱 garden, ign to gz

#1070 Add SDF::SetRoot and deprecate non-const SDF::Root
  Migration.md
  include/sdf/SDFImpl.hh
  src/SDF.cc
  src/SDF_TEST.cc
  src/parser.cc
  test/integration/deprecated_specs.cc
Labels: 🌱 garden

#1027 Get the world name
  include/sdf/Root.hh
  src/Root.cc
  src/Root_TEST.cc
Labels: 🌱 garden, OOBE 📦✨

#1074 Find GzURDFDOM, fix warning
  CMakeLists.txt
  src/CMakeLists.txt
Labels: 🌱 garden

#1076 Set protocol version to 1.10
  CMakeLists.txt
Labels: 🌱 garden

#1080 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, Gazebo 1️1️, QA

#1050 Accept moon and custom surfaces in world spherical coordinates
  sdf/1.10/spherical_coordinates.sdf
  src/World.cc
  src/World_TEST.cc
Labels: 🌱 garden

#1067 Replace custom SDF_* macros with GZ_*
  Migration.md
  include/sdf/InterfaceElements.hh
  include/sdf/Types.hh
  src/InterfaceElements.cc
Labels: 🌱 garden

#1081 Remove unused sdf.hh.in template
  include/sdf/sdf.hh.in
Labels: 🏯 fortress

#1082 Merge sdf12 ➡️ main
  include/sdf/Sky.hh
  include/sdf/sdf.hh.in
  sdf/1.10/scene.sdf
  sdf/1.9/scene.sdf
  src/Sky.cc
  src/Sky_TEST.cc
  test/integration/scene_dom.cc
  test/sdf/scene_with_sky.sdf
Labels: 🌱 garden

#1083 Added Shininess to Material Python wrapper
  python/src/sdf/pyMaterial.cc
  python/test/pyMaterial_TEST.py
Labels: scripting, 🌱 garden

#1087 9 ➡️ 12
  CMakeLists.txt
  README.md
  include/sdf/Link.hh
  src/Link.cc
  src/cmd/CMakeLists.txt
  src/cmd/sdf.bash_completion.sh
  src/ign.cc
  src/ign_TEST.cc
Labels: 🏯 fortress

#1085 Added Sky Cubemap methods to Python
  python/src/sdf/pySky.cc
  python/test/pySky_TEST.py
Labels: scripting, 🌱 garden

#1066 Test using `__model__`, `world` in @attached_to, @relative_to
  src/FrameSemantics_TEST.cc
  src/Model.cc
  src/parser.cc
  test/integration/frame.cc
  test/integration/link_dom.cc
  test/sdf/model_frame_attached_to.sdf
  test/sdf/model_link_relative_to.sdf
  test/sdf/world_frame_attached_to.sdf
  test/sdf/world_frame_relative_to.sdf
Labels: 🏰 citadel, Gazebo 1️1️

#1091 Merge sdf9 ➡️ sdf12
  src/FrameSemantics_TEST.cc
  src/Model.cc
  src/parser.cc
  test/integration/frame.cc
  test/integration/link_dom.cc
  test/integration/root_dom.cc
  test/sdf/model_frame_attached_to.sdf
  test/sdf/model_link_relative_to.sdf
  test/sdf/world_frame_attached_to.sdf
  test/sdf/world_frame_relative_to.sdf
Labels: 🏯 fortress

#1079 Test model name as placement_frame
  test/integration/nested_model.cc
  test/sdf/placement_frame.sdf
Labels: 🏯 fortress

#1084 Added Polyline Python interface
  python/CMakeLists.txt
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyPolyline.cc
  python/src/sdf/pyPolyline.hh
  python/test/pyPolyline_TEST.py
Labels: scripting, 🌱 garden

#1092 Install python3-gz-math7 instead of ignition
  .github/ci/packages.apt
Labels: 🌱 garden

#844 Change Root to non-unique impl pointer
  include/sdf/Frame.hh
  include/sdf/Root.hh
  src/Frame.cc
  src/Frame_TEST.cc
  src/Model.cc
  src/Model_TEST.cc
  src/Root.cc
  src/Root_TEST.cc
  src/World.cc
  src/World_TEST.cc
Labels: enhancement, 🌱 garden, Breaking change

#1093 Backport #419: Ensure relocatable config files
  CMakeLists.txt
  cmake/sdf_config.cmake.in
  cmake/sdformat_pc.in
Labels: 🏰 citadel, Gazebo 1️1️

#1089 Fix URDF fixed joint reduction of SDF joints
  src/parser_urdf.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/fixed_joint_reduction_joint_frame_extension.urdf
Labels: bug, 🏯 fortress

#1077 Add fluid added mass to inertial
  sdf/1.10/inertial.sdf
  src/Link.cc
  src/Link_TEST.cc
  test/integration/link_dom.cc
  test/sdf/inertial_complete.sdf
Labels: enhancement, 🌱 garden, MBARI buoy

#1097 InterfaceElements: remove deprecated variables
  include/sdf/InterfaceElements.hh
  src/InterfaceElements.cc
Labels: 🌱 garden, Breaking change

#1096 Warn by default on unrecognized elements
  Migration.md
  src/ParserConfig.cc
  src/gz_TEST.cc
Labels: bug, 🌱 garden, Breaking change

#1099 Add Error enums and update Migration guide
  Migration.md
  include/sdf/Error.hh
  src/gz_TEST.cc
Labels: 🌱 garden, Breaking change

#1101 Make //plugin/@name optional
  Migration.md
  sdf/1.10/plugin.sdf
  src/Plugin.cc
  src/Plugin_TEST.cc
  src/parser.cc
Labels: 🌱 garden, Breaking change
