Repository gazebosim/sdformat, pull requests merged in 2022-09, with the labels that each got.

#1127 Add pybind11 module as MODULE
  python/CMakeLists.txt
Labels: bug, 🌱 garden

#1132 Prepare for 12.6.0~pre1 release
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🏯 fortress

#1133 Merge sdf9 ➡️ sdf12
  Migration.md
  include/sdf/Camera.hh
  sdf/1.7/camera.sdf
  sdf/1.8/camera.sdf
  sdf/1.9/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏯 fortress

#1134 Prepare for 9.9.0~pre1 prerelease
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#1139 Update Changelog for 13.0.0
  Changelog.md
Labels: 🌱 garden

#1142 Change gz-math python to gz.math7
  python/test/pyAirPressure_TEST.py
  python/test/pyAltimeter_TEST.py
  python/test/pyAtmosphere_TEST.py
  python/test/pyBox_TEST.py
  python/test/pyCamera_TEST.py
  python/test/pyCapsule_TEST.py
  python/test/pyCollision_TEST.py
  python/test/pyCylinder_TEST.py
  python/test/pyEllipsoid_TEST.py
  python/test/pyFrame_TEST.py
  python/test/pyGeometry_TEST.py
  python/test/pyHeightmap_TEST.py
  python/test/pyIMU_TEST.py
  python/test/pyJointAxis_TEST.py
  python/test/pyJoint_TEST.py
  python/test/pyLidar_TEST.py
  python/test/pyLight_TEST.py
  python/test/pyLink_TEST.py
  python/test/pyMagnetometer_TEST.py
  python/test/pyMaterial_TEST.py
  python/test/pyMesh_TEST.py
  python/test/pyModel_TEST.py
  python/test/pyParticleEmitter_TEST.py
  python/test/pyPlane_TEST.py
  python/test/pyPolyline_TEST.py
  python/test/pyRoot_TEST.py
  python/test/pyScene_TEST.py
  python/test/pySemanticPose_TEST.py
  python/test/pySensor_TEST.py
  python/test/pySky_TEST.py
  python/test/pySphere_TEST.py
  python/test/pySurface_TEST.py
  python/test/pyVisual_TEST.py
  python/test/pyWorld_TEST.py
Labels: bug, 🌱 garden

#1143 Use versioned python module name
  python/CMakeLists.txt
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/test/pyAirPressure_TEST.py
  python/test/pyAltimeter_TEST.py
  python/test/pyAtmosphere_TEST.py
  python/test/pyBox_TEST.py
  python/test/pyCamera_TEST.py
  python/test/pyCapsule_TEST.py
  python/test/pyCollision_TEST.py
  python/test/pyCylinder_TEST.py
  python/test/pyEllipsoid_TEST.py
  python/test/pyError_TEST.py
  python/test/pyForceTorque_TEST.py
  python/test/pyFrame_TEST.py
  python/test/pyGeometry_TEST.py
  python/test/pyGui_TEST.py
  python/test/pyHeightmap_TEST.py
  python/test/pyIMU_TEST.py
  python/test/pyJointAxis_TEST.py
  python/test/pyJoint_TEST.py
  python/test/pyLidar_TEST.py
  python/test/pyLight_TEST.py
  python/test/pyLink_TEST.py
  python/test/pyMagnetometer_TEST.py
  python/test/pyMaterial_TEST.py
  python/test/pyMesh_TEST.py
  python/test/pyModel_TEST.py
  python/test/pyNavSat_TEST.py
  python/test/pyNoise_TEST.py
  python/test/pyParserConfig_TEST.py
  python/test/pyParticleEmitter_TEST.py
  python/test/pyPbr_TEST.py
  python/test/pyPhysics_TEST.py
  python/test/pyPlane_TEST.py
  python/test/pyPlugin_TEST.py
  python/test/pyPolyline_TEST.py
  python/test/pyRoot_TEST.py
  python/test/pyScene_TEST.py
  python/test/pySemanticPose_TEST.py
  python/test/pySensor_TEST.py
  python/test/pySky_TEST.py
  python/test/pySphere_TEST.py
  python/test/pySurface_TEST.py
  python/test/pyVisual_TEST.py
  python/test/pyWorld_TEST.py
Labels: 🌱 garden

#1146 Update for 13.0.0~pre2
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1126 urdf: fix test and clean up internals
  src/parser_urdf.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: bug, 🏰 citadel, Gazebo 1️1️

#1167 Merge sdf9 ➡️ sdf12
  Changelog.md
  src/parser_urdf.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🏯 fortress

#1169 13.0.0 release
  CMakeLists.txt
Labels: 🌱 garden

#1170 Reduce the number of include dirs for sdformat
  src/CMakeLists.txt
Labels: 🏯 fortress

#1173 Fix arm tests
  src/gz_TEST.cc
  test/integration/error_output.cc
Labels: 🌱 garden

#1175 Prepare for 13.0.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1174 12.0.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1137 Param::Set: fix truncation of floating-point values
  include/sdf/Param.hh
  src/Param_TEST.cc
  src/World_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/precision.cc
Labels: 🌱 garden

#1148 parser_urdf: add //frame for reduced links/joints
  src/parser_urdf.cc
  test/integration/fixed_joint_example.urdf
  test/integration/fixed_joint_simple.urdf
  test/integration/urdf_gazebo_extensions.cc
Labels: 🏰 citadel, Gazebo 1️1️

#1177 Merge sdf12 ➡️ sdf13
  Changelog.md
  Migration.md
  include/sdf/Camera.hh
  sdf/1.10/camera.sdf
  sdf/1.7/camera.sdf
  sdf/1.8/camera.sdf
  sdf/1.9/camera.sdf
  src/CMakeLists.txt
  src/Camera.cc
  src/Camera_TEST.cc
  src/parser_urdf.cc
  test/integration/link_dom.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
  test/sdf/sensors.sdf
Labels: 🌱 garden

#1176 Merge sdf9 ➡️ sdf12
  src/parser_urdf.cc
  test/integration/fixed_joint_example.urdf
  test/integration/fixed_joint_simple.urdf
  test/integration/urdf_gazebo_extensions.cc
Labels: 🏯 fortress

#1178 Prepare for 9.9.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#1130 python: Import gz.math at startup to fix #1129
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/test/pyAirPressure_TEST.py
  python/test/pyAltimeter_TEST.py
  python/test/pyAtmosphere_TEST.py
  python/test/pyCapsule_TEST.py
  python/test/pyCylinder_TEST.py
  python/test/pyEllipsoid_TEST.py
  python/test/pyJointAxis_TEST.py
  python/test/pyLidar_TEST.py
  python/test/pyMagnetometer_TEST.py
  python/test/pyModel_TEST.py
  python/test/pyPlane_TEST.py
  python/test/pyRoot_TEST.py
  python/test/pySphere_TEST.py
  python/test/pyWorld_TEST.py
Labels: 🌱 garden
