Repository gazebosim/sdformat, pull requests merged in 2022-01, with the labels that each got.

#809 Fix parsing 'type' attibutes in plugins
  src/Param.cc
  src/Plugin_TEST.cc
  src/parser.cc
Labels: 🏯 fortress

#797 Added articulationRootAPI to SDF-USD converter
  src/usd/sdf_usd_parser/joint.cc
  src/usd/sdf_usd_parser/world.cc
Labels: 🌱 garden

#815 Add ParserConfig flag for preserveFixedJoint
  include/sdf/ParserConfig.hh
  src/ParserConfig.cc
  src/parser.cc
  src/parser_urdf.cc
  src/parser_urdf.hh
  src/parser_urdf_TEST.cc
Labels: 🏯 fortress

#819 USD -> SDF: polygon triangulation
  src/CMakeLists.txt
  src/usd/usd_parser/polygon_helper.cc
  src/usd/usd_parser/utils.cc
Labels: 🏯 fortress

#823 11 ➡️ 12
  include/sdf/ParserConfig.hh
  src/ParserConfig.cc
  src/parser.cc
  src/parser_urdf.cc
  src/parser_urdf.hh
  src/parser_urdf_TEST.cc
Labels: 🏯 fortress

#817 make SDF to USD a separate component of sdformat
  .github/ci/before_cmake.sh
  .github/ci/packages.apt
  .github/workflows/ci.yml
  CMakeLists.txt
  examples/usdConverter/README.md
  test/test_utils.hh
  usd/include/sdf/CMakeLists.txt
  usd/include/sdf/usd/sdf_parser/World.hh
  usd/src/CMakeLists.txt
  usd/src/cmd/CMakeLists.txt
  usd/src/cmd/sdf2usd.cc
  usd/src/sdf_parser/World.cc
  usd/src/sdf_parser/World_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/sdf2usd_TEST.cc
Labels: 🏯 fortress

#824 Adding _config to readFile call
  src/parser.cc
  test/integration/model/simple_model/model.config
  test/integration/model/simple_model/model.sdf
  test/integration/model/sub_nested/model.config
  test/integration/model/sub_nested/model.sdf
  test/integration/model/top_nested/model.config
  test/integration/model/top_nested/model.sdf
  test/integration/parser_config.cc
Labels: 🏯 fortress

#833 Allow model frames (__model__) to be used as joint parent or child
  src/parser.cc
  test/integration/joint_dom.cc
  test/sdf/joint_child_model_frame.sdf
  test/sdf/joint_nested_parent_child.sdf
  test/sdf/joint_parent_model_frame.sdf
Labels: 🏢 edifice

#834 11 ➡️ 12
  src/parser.cc
  test/integration/joint_dom.cc
  test/sdf/joint_child_model_frame.sdf
  test/sdf/joint_nested_parent_child.sdf
  test/sdf/joint_parent_model_frame.sdf
Labels: 🏯 fortress

#835 Handle __model__ in joint parent or child when using merge-include
  src/parser.cc
  test/integration/includes.cc
  test/integration/model/merge_robot/model.sdf
Labels: 🏯 fortress
