Repository gazebosim/sdformat, pull requests merged in 2022-10, with the labels that each got.

#1182 Merge sdf12 ➡️ sdf13
  src/parser_urdf.cc
  test/integration/fixed_joint_example.urdf
  test/integration/fixed_joint_simple.urdf
  test/integration/urdf_gazebo_extensions.cc
Labels: 🌱 garden

#1147 Add a configuration option to resolve URIs
  include/sdf/Collision.hh
  include/sdf/Geometry.hh
  include/sdf/Heightmap.hh
  include/sdf/Link.hh
  include/sdf/Material.hh
  include/sdf/Mesh.hh
  include/sdf/ParserConfig.hh
  include/sdf/Scene.hh
  include/sdf/Sky.hh
  include/sdf/Visual.hh
  src/Collision.cc
  src/Geometry.cc
  src/Heightmap.cc
  src/Link.cc
  src/Material.cc
  src/Mesh.cc
  src/Model.cc
  src/ParserConfig.cc
  src/ParserConfig_TEST.cc
  src/Scene.cc
  src/Sky.cc
  src/Utils.cc
  src/Utils.hh
  src/Visual.cc
  src/World.cc
  test/integration/CMakeLists.txt
  test/integration/resolve_uris.cc
  test/sdf/resolve_uris.sdf
Labels: 🌱 garden

#1180 Add test helper python package for encapsulating versioned python packages
  python/test/gz_test_deps/README
  python/test/gz_test_deps/__init__.py
  python/test/gz_test_deps/math.py
  python/test/gz_test_deps/sdformat.py
  python/test/pyAirPressure_TEST.py
  python/test/pyAltimeter_TEST.py
  python/test/pyAtmosphere_TEST.py
  python/test/pyBox_TEST.py
  python/test/pyCamera_TEST.py
  python/test/pyCapsule_TEST.py
  python/test/pyCollision_TEST.py
  python/test/pyCylinder_TEST.py
  python/test/pyEllipsoid_TEST.py
  python/test/pyError_TEST.py
  python/test/pyForceTorque_TEST.py
  python/test/pyFrame_TEST.py
  python/test/pyGeometry_TEST.py
  python/test/pyGui_TEST.py
  python/test/pyHeightmap_TEST.py
  python/test/pyIMU_TEST.py
  python/test/pyJointAxis_TEST.py
  python/test/pyJoint_TEST.py
  python/test/pyLidar_TEST.py
  python/test/pyLight_TEST.py
  python/test/pyLink_TEST.py
  python/test/pyMagnetometer_TEST.py
  python/test/pyMaterial_TEST.py
  python/test/pyMesh_TEST.py
  python/test/pyModel_TEST.py
  python/test/pyNavSat_TEST.py
  python/test/pyNoise_TEST.py
  python/test/pyParserConfig_TEST.py
  python/test/pyParticleEmitter_TEST.py
  python/test/pyPbr_TEST.py
  python/test/pyPhysics_TEST.py
  python/test/pyPlane_TEST.py
  python/test/pyPlugin_TEST.py
  python/test/pyPolyline_TEST.py
  python/test/pyRoot_TEST.py
  python/test/pyScene_TEST.py
  python/test/pySemanticPose_TEST.py
  python/test/pySensor_TEST.py
  python/test/pySky_TEST.py
  python/test/pySphere_TEST.py
  python/test/pySurface_TEST.py
  python/test/pyVisual_TEST.py
  python/test/pyWorld_TEST.py
Labels: 🌱 garden

#1185 🎈 13.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1122 Model: add sdf::Errors output to API methods
  src/Model.cc
  test/integration/error_output.cc
  test/integration/joint_dom.cc
Labels: enhancement

#1117 sdf/1.10: support //world/joint specification
  Migration.md
  include/sdf/Joint.hh
  include/sdf/ParserConfig.hh
  include/sdf/World.hh
  python/src/sdf/pyWorld.cc
  python/test/pyWorld_TEST.py
  sdf/1.10/joint.sdf
  sdf/1.10/world.sdf
  src/FrameSemantics.cc
  src/World.cc
  src/World_TEST.cc
  src/gz_TEST.cc
  test/integration/joint_dom.cc
  test/integration/nested_model.cc
  test/sdf/world_joint_child_frame.sdf
  test/sdf/world_joint_invalid_child_world.sdf
  test/sdf/world_joint_parent_frame.sdf
Labels: enhancement, 🌱 garden

#1168 sdf/1.10/joint.sdf: add screw_thread_pitch
  Migration.md
  include/sdf/Joint.hh
  python/src/sdf/pyJoint.cc
  python/test/pyJoint_TEST.py
  sdf/1.10/joint.sdf
  sdf/1.4/joint.sdf
  sdf/1.5/joint.sdf
  sdf/1.6/joint.sdf
  sdf/1.7/joint.sdf
  sdf/1.8/joint.sdf
  sdf/1.9/joint.sdf
  src/Joint.cc
  src/Joint_TEST.cc
  test/integration/joint_dom.cc
  test/sdf/joint_screw_thread_pitch.sdf
Labels: 🌱 garden

#1121 Added Root::WorldByName
  include/sdf/Root.hh
  src/Root.cc
  src/Root_TEST.cc
Labels: enhancement, 🌱 garden

#1165 Rename python bindings import library for Windows
  python/CMakeLists.txt
Labels: 🌱 garden

#1183 Fix GZ_PYTHON_INSTALL_PATH value
  python/CMakeLists.txt
Labels: 🌱 garden

#1184 Python: Added OpticalFrameID and SetOpticalFrameID to pyCamera
  python/src/sdf/pyCamera.cc
  python/test/pyCamera_TEST.py
Labels: 🌱 garden

#1191 Prepare for 13.2.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden
