Repository gazebosim/sdformat, pull requests merged in 2022-05, with the labels that each got.

#907 Changes for replacing PythonInterp with Python3
  test/integration/CMakeLists.txt
Labels: needs upstream release, 🌱 garden

#1008 ign -> gz Header Migration : sdformat
  include/sdf/Actor.hh
  include/sdf/AirPressure.hh
  include/sdf/Altimeter.hh
  include/sdf/Atmosphere.hh
  include/sdf/Box.hh
  include/sdf/Camera.hh
  include/sdf/Capsule.hh
  include/sdf/Collision.hh
  include/sdf/Cylinder.hh
  include/sdf/Ellipsoid.hh
  include/sdf/Error.hh
  include/sdf/Exception.hh
  include/sdf/Filesystem.hh
  include/sdf/ForceTorque.hh
  include/sdf/Frame.hh
  include/sdf/Geometry.hh
  include/sdf/Gui.hh
  include/sdf/Heightmap.hh
  include/sdf/Imu.hh
  include/sdf/InterfaceElements.hh
  include/sdf/InterfaceFrame.hh
  include/sdf/InterfaceJoint.hh
  include/sdf/InterfaceLink.hh
  include/sdf/InterfaceModel.hh
  include/sdf/InterfaceModelPoseGraph.hh
  include/sdf/Joint.hh
  include/sdf/JointAxis.hh
  include/sdf/Lidar.hh
  include/sdf/Light.hh
  include/sdf/Link.hh
  include/sdf/Magnetometer.hh
  include/sdf/Material.hh
  include/sdf/Mesh.hh
  include/sdf/Model.hh
  include/sdf/NavSat.hh
  include/sdf/Noise.hh
  include/sdf/OutputConfig.hh
  include/sdf/Param.hh
  include/sdf/ParserConfig.hh
  include/sdf/ParticleEmitter.hh
  include/sdf/Pbr.hh
  include/sdf/Physics.hh
  include/sdf/Plane.hh
  include/sdf/PrintConfig.hh
  include/sdf/Root.hh
  include/sdf/Scene.hh
  include/sdf/SemanticPose.hh
  include/sdf/Sensor.hh
  include/sdf/Sky.hh
  include/sdf/Sphere.hh
  include/sdf/Surface.hh
  include/sdf/Visual.hh
  include/sdf/World.hh
  usd/include/sdf/usd/UsdError.hh
  usd/include/sdf/usd/usd_parser/USDData.hh
  usd/include/sdf/usd/usd_parser/USDStage.hh
  usd/include/sdf/usd/usd_parser/USDTransforms.hh
Labels: 🌱 garden

#967 Added Root Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyRoot.cc
  python/src/sdf/pyRoot.hh
  python/test/pyRoot_TEST.py
Labels: scripting, 🌱 garden, mujoco

#975 SDF to USD: Added Material Physics
  test/sdf/ellipsoid_model.sdf
  usd/src/sdf_parser/Collision.cc
  usd/src/sdf_parser/sdf2usd_TEST.cc
Labels: usd

#939 Adding sdf::Error logging to Param
  include/sdf/Error.hh
  include/sdf/Param.hh
  src/Param.cc
  test/integration/CMakeLists.txt
  test/integration/error_output.cc
Labels: 🌱 garden

#990 Fix ambiguities in spec inertial documentation
  sdf/1.4/inertial.sdf
  sdf/1.5/inertial.sdf
  sdf/1.6/inertial.sdf
  sdf/1.7/inertial.sdf
  sdf/1.8/inertial.sdf
  sdf/1.9/inertial.sdf
Labels: 🏯 fortress

#1009 12 ➡️ 13 (main)
  include/sdf/Plugin.hh
  src/Plugin.cc
  src/Plugin_TEST.cc
  test/usd/upAxisZ.usda
  usd/include/sdf/usd/usd_parser/Parser.hh
  usd/src/cmd/usd2sdf.cc
  usd/src/usd_parser/Parser.cc
  usd/src/usd_parser/USD2SDF.cc
  usd/src/usd_parser/USD2SDF.hh
  usd/src/usd_parser/USDLinks.cc
  usd/src/usd_parser/USDStage_TEST.cc
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/USDWorld.hh
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: 🌱 garden

#989 Added Light Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyLight.cc
  python/src/sdf/pyLight.hh
  python/test/pyLight_TEST.py
Labels: scripting, 🌱 garden, mujoco

#994 Added Pbr and PbrWorkflow Python interfaces
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyMaterial.cc
  python/src/sdf/pyPbr.cc
  python/src/sdf/pyPbr.hh
  python/test/pyMaterial_TEST.py
  python/test/pyPbr_TEST.py
Labels: scripting, 🌱 garden, mujoco

#1013 Added light methods to Link, Root and World
  python/src/sdf/pyLink.cc
  python/src/sdf/pyRoot.cc
  python/src/sdf/pyWorld.cc
  python/test/pyLink_TEST.py
  python/test/pyRoot_TEST.py
  python/test/pyWorld_TEST.py
Labels: 🌱 garden

#1014 Remove warnings on main
  usd/src/sdf_parser/Geometry.cc
  usd/src/usd_parser/USDLights.cc
Labels: 🌱 garden

#970 Added Altimeter Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyAltimeter.cc
  python/src/sdf/pyAltimeter.hh
  python/test/pyAltimeter_TEST.py
Labels: scripting, 🌱 garden, mujoco

#968 Added Atmosphere Python interface
  include/sdf/Atmosphere.hh
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyAtmosphere.cc
  python/src/sdf/pyAtmosphere.hh
  python/test/pyAtmosphere_TEST.py
  src/Atmosphere.cc
Labels: scripting, 🌱 garden, mujoco

#1006 Camera: fix default trigger topic
  sdf/1.9/camera.sdf
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏯 fortress

#1015 Add visibility mask to Lidar / Ray sensor
  include/sdf/Lidar.hh
  sdf/1.9/lidar.sdf
  sdf/1.9/ray.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/Visual.cc
  src/Visual_TEST.cc
Labels: 🏯 fortress

#1017 🎈 12.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1024 Merge sdf12 ➡️ main
  Changelog.md
  include/sdf/Cylinder.hh
  include/sdf/Geometry.hh
  include/sdf/Lidar.hh
  include/sdf/Material.hh
  include/sdf/Polyline.hh
  sdf/1.4/inertial.sdf
  sdf/1.5/inertial.sdf
  sdf/1.6/inertial.sdf
  sdf/1.7/inertial.sdf
  sdf/1.7/material.sdf
  sdf/1.8/inertial.sdf
  sdf/1.8/material.sdf
  sdf/1.9/camera.sdf
  sdf/1.9/inertial.sdf
  sdf/1.9/lidar.sdf
  sdf/1.9/material.sdf
  sdf/1.9/ray.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  src/Geometry.cc
  src/Geometry_TEST.cc
  src/Lidar.cc
  src/Lidar_TEST.cc
  src/Material.cc
  src/Material_TEST.cc
  src/Polyline.cc
  src/Polyline_TEST.cc
  src/Visual.cc
  src/Visual_TEST.cc
  test/integration/geometry_dom.cc
  test/integration/link_dom.cc
  test/sdf/ellipsoid_model.sdf
  test/sdf/sensors.sdf
  test/sdf/shapes.sdf
  usd/src/sdf_parser/Collision.cc
  usd/src/sdf_parser/sdf2usd_TEST.cc
Labels: 🌱 garden

#1020 Python interfaces: Added to string method to Root
  python/src/sdf/pyRoot.cc
  python/test/pyRoot_TEST.py
Labels: scripting, 🌱 garden, mujoco

#981 Added IMU python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyIMU.cc
  python/src/sdf/pyIMU.hh
  python/test/pyIMU_TEST.py
Labels: scripting, 🌱 garden, mujoco

#982 Added Camera Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyCamera.cc
  python/src/sdf/pyCamera.hh
  python/test/pyCamera_TEST.py
Labels: scripting, 🌱 garden, mujoco

#983 Added ForceTorque Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyForceTorque.cc
  python/src/sdf/pyForceTorque.hh
  python/test/pyForceTorque_TEST.py
Labels: scripting, 🌱 garden, mujoco

#984 Added NavSat Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyNavSat.cc
  python/src/sdf/pyNavSat.hh
  python/test/pyNavSat_TEST.py
Labels: scripting, 🌱 garden, mujoco

#972 Added Magnetometer Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyMagnetometer.cc
  python/src/sdf/pyMagnetometer.hh
  python/test/pyMagnetometer_TEST.py
Labels: scripting, 🌱 garden, mujoco

#973 Added Lidar Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyLidar.cc
  python/src/sdf/pyLidar.hh
  python/test/pyLidar_TEST.py
Labels: scripting, 🌱 garden, mujoco

#988 Added Sensor Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pySensor.cc
  python/src/sdf/pySensor.hh
  python/test/pySensor_TEST.py
Labels: scripting, 🌱 garden, mujoco

#1012 Add Link::ResolveInertial API
  include/sdf/Link.hh
  src/Link.cc
  src/ign.cc
Labels: 🏰 citadel, Gazebo 1️1️

#1028 Python interfaces: Added Sensor to Link and Joint
  python/src/sdf/pyJoint.cc
  python/src/sdf/pyLink.cc
  python/test/pyJoint_TEST.py
  python/test/pyLink_TEST.py
Labels: 🌱 garden

#1031 sdf::Joint: Mutable versions of SensorByName and SensorByIndex
  include/sdf/Joint.hh
  src/Joint.cc
  src/Joint_TEST.cc
Labels: 🏯 fortress

#1032 sdf12 to main
  include/sdf/Joint.hh
  python/src/sdf/pyJoint.cc
  python/test/pyJoint_TEST.py
  src/Joint.cc
  src/Joint_TEST.cc
Labels: 🌱 garden

#1033 Fix bug with resolving poses for joint sensors.
  include/sdf/Sensor.hh
  src/Joint.cc
  test/integration/joint_dom.cc
Labels: 🏯 fortress

#1034 12 ➡️ main
  include/sdf/Sensor.hh
  src/Joint.cc
  test/integration/joint_dom.cc
Labels: 🌱 garden
