Repository gazebosim/sdformat, pull requests merged in 2022-06, with the labels that each got.

#1036 Add Friction, ODE python interfaces
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pySurface.cc
  python/src/sdf/pySurface.hh
  python/test/pySurface_TEST.py
Labels: 🌱 garden, mujoco

#1039 Use pose multiplication instead of subtraction
  usd/src/usd_parser/USDSensors.cc
Labels: 🌱 garden

#1043 Don't include the gz/math.hh header from library code
  include/sdf/Link.hh
  include/sdf/Param.hh
  src/parser_urdf.cc
Labels: 🌱 garden

#1019 deprecate inertia
  Migration.md
  include/sdf/Types.hh
Labels: 🌱 garden

#993 Added Heightmap, HeightmapBlend and HeightmapTexture Python interfaces
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyHeightmap.cc
  python/src/sdf/pyHeightmap.hh
  python/test/pyHeightmap_TEST.py
  src/Heightmap_TEST.cc
Labels: scripting, 🌱 garden, mujoco

#996 Added Sky Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pySky.cc
  python/src/sdf/pySky.hh
  python/test/pySky_TEST.py
Labels: scripting, 🌱 garden, mujoco

#1042 Bash completion for flags
  cmake/SearchForStuff.cmake
  src/cmd/CMakeLists.txt
  src/cmd/sdf.bash_completion.sh
  src/ign_TEST.cc
Labels: 🏰 citadel, Gazebo 1️1️, OOBE 📦✨

#1052 [ign -> gz] CMake functions
  CMakeLists.txt
  conf/CMakeLists.txt
  conf/sdformat.yaml.in
  include/sdf/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  usd/include/sdf/CMakeLists.txt
  usd/src/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#1053 Joint: rename parent/child *LinkName APIs
  Migration.md
  include/sdf/Joint.hh
  include/sdf/parser.hh
  python/src/sdf/pyJoint.cc
  python/test/pyJoint_TEST.py
  src/FrameSemantics.cc
  src/Joint.cc
  src/Joint_TEST.cc
  src/ign.cc
  src/parser.cc
  test/integration/includes.cc
  test/integration/joint_dom.cc
  test/integration/sdf_dom_conversion.cc
  usd/src/sdf_parser/Joint.cc
  usd/src/sdf_parser/Joint_Sdf2Usd_TEST.cc
  usd/src/usd_parser/USDJoints.cc
  usd/src/usd_parser/USDJoints_TEST.cc
Labels: 🌱 garden

#1049 Surface::ToElement: add //friction/ode/mu
  src/Collision_TEST.cc
  src/Surface.cc
Labels: 🌱 garden, mujoco

#992 Added Scene Python interfaace
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyScene.cc
  python/src/sdf/pyScene.hh
  python/test/pyScene_TEST.py
  src/Scene_TEST.cc
Labels: scripting, 🌱 garden, mujoco

#1047 ign -> gz CLI Migration : sdformat
  CMakeLists.txt
  Changelog.md
  Migration.md
  README.md
  conf/CMakeLists.txt
  src/CMakeLists.txt
  src/Param.cc
  src/cmd/CMakeLists.txt
  src/cmd/cmdsdformat.rb.in
  src/gz.cc
  src/gz.hh
  src/gz_TEST.cc
  src/parser_TEST.cc
  test/sdf/inertial_stats.sdf
Labels: 🌱 garden, ign to gz

#1055 Update return types for Plugin's Name and Filename
  include/sdf/Plugin.hh
  src/Plugin.cc
Labels: 🌱 garden

#1045 Update dependency CMake projects to gz
  CMakeLists.txt
  python/CMakeLists.txt
  src/CMakeLists.txt
  usd/src/CMakeLists.txt
  usd/src/cmd/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#1057 Migrate IGNITION- CMake variables
  src/gz_TEST.cc
  test/CMakeLists.txt
  test/test_config.h.in
Labels: 🌱 garden, ign to gz

#1058 ign -> gz Partial Docs Migration and Project Name Followups : sdformat
  CMakeLists.txt
  Changelog.md
  README.md
  examples/usdConverter/README.md
  src/CMakeLists.txt
  usd/src/usd_parser/USDLights.cc
Labels: 🌱 garden

#1060 Added Python Exceptions that wrap sdf::Errors
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyExceptions.hh
  python/src/sdf/pyFrame.cc
  python/test/pyFrame_TEST.py
Labels: 🌱 garden, mujoco

#1061 Wrap sdf::Errors with exceptions in all python bindings
  python/CMakeLists.txt
  python/src/sdf/pyFrame.cc
  python/src/sdf/pyJoint.cc
  python/src/sdf/pyJointAxis.cc
  python/src/sdf/pyModel.cc
  python/src/sdf/pyRoot.cc
  python/src/sdf/pySemanticPose.cc
  python/src/sdf/pybind11_helpers.cc
  python/src/sdf/pybind11_helpers.hh
  python/test/pyCollision_TEST.py
  python/test/pyFrame_TEST.py
  python/test/pyJointAxis_TEST.py
  python/test/pyJoint_TEST.py
  python/test/pyLight_TEST.py
  python/test/pyLink_TEST.py
  python/test/pyModel_TEST.py
  python/test/pyRoot_TEST.py
  python/test/pySensor_TEST.py
  python/test/pyVisual_TEST.py
Labels: scripting, 🌱 garden, mujoco

#1062 Fixed test CMakelists.txt
  test/CMakeLists.txt
Labels: 🌱 garden

#999 Added Particle Emitter Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyParticleEmitter.cc
  python/src/sdf/pyParticleEmitter.hh
  python/test/pyParticleEmitter_TEST.py
Labels: scripting, 🌱 garden, mujoco

#995 Added Physics Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyPhysics.cc
  python/src/sdf/pyPhysics.hh
  python/src/sdf/pyWorld.cc
  python/test/pyPhysics_TEST.py
  python/test/pyWorld_TEST.py
Labels: scripting, 🌱 garden, mujoco

#998 Added Gui Python interface
  python/CMakeLists.txt
  python/src/sdf/_ignition_sdformat_pybind11.cc
  python/src/sdf/pyGui.cc
  python/src/sdf/pyGui.hh
  python/src/sdf/pyWorld.cc
  python/test/pyGui_TEST.py
  python/test/pyWorld_TEST.py
Labels: scripting, 🌱 garden, mujoco
