Repository gazebosim/sdformat, pull requests merged in 2022-03, with the labels that each got.

#846 Triggered Camera
  include/sdf/Camera.hh
  sdf/1.9/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
Labels: 🏯 fortress

#858 Use the Plugin DOM in other DOM objects
  include/sdf/Actor.hh
  include/sdf/Gui.hh
  include/sdf/Model.hh
  include/sdf/Plugin.hh
  include/sdf/Sensor.hh
  include/sdf/Visual.hh
  include/sdf/World.hh
  src/Actor.cc
  src/Actor_TEST.cc
  src/Gui.cc
  src/Gui_TEST.cc
  src/Model.cc
  src/Model_TEST.cc
  src/ParamPassing.cc
  src/Plugin_TEST.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  src/Visual.cc
  src/Visual_TEST.cc
  src/World.cc
  src/World_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/actor_dom.cc
  test/integration/gui_dom.cc
  test/integration/model_dom.cc
  test/integration/param_passing.cc
  test/integration/sensor_dom.cc
  test/integration/visual_dom.cc
  test/integration/world_dom.cc
  test/sdf/world_complete.sdf
Labels: 🏯 fortress

#831 sdf -> usd: Materials
  test/sdf/basic_shapes.sdf
  usd/include/sdf/usd/Conversions.hh
  usd/include/sdf/usd/UsdError.hh
  usd/include/sdf/usd/sdf_parser/Material.hh
  usd/src/CMakeLists.txt
  usd/src/Conversions.cc
  usd/src/Conversions_TEST.cc
  usd/src/cmd/sdf2usd.cc
  usd/src/sdf_parser/Geometry.cc
  usd/src/sdf_parser/Material.cc
  usd/src/sdf_parser/Material_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/Visual.cc
Labels: usd

#842 Root to element
  include/sdf/Actor.hh
  include/sdf/AirPressure.hh
  include/sdf/Altimeter.hh
  include/sdf/Atmosphere.hh
  include/sdf/Box.hh
  include/sdf/Camera.hh
  include/sdf/Capsule.hh
  include/sdf/Collision.hh
  include/sdf/Cylinder.hh
  include/sdf/Ellipsoid.hh
  include/sdf/ForceTorque.hh
  include/sdf/Geometry.hh
  include/sdf/Gui.hh
  include/sdf/Heightmap.hh
  include/sdf/Imu.hh
  include/sdf/Joint.hh
  include/sdf/JointAxis.hh
  include/sdf/Lidar.hh
  include/sdf/Light.hh
  include/sdf/Link.hh
  include/sdf/Magnetometer.hh
  include/sdf/Material.hh
  include/sdf/Mesh.hh
  include/sdf/Model.hh
  include/sdf/Noise.hh
  include/sdf/ParticleEmitter.hh
  include/sdf/Physics.hh
  include/sdf/Plane.hh
  include/sdf/Plugin.hh
  include/sdf/Root.hh
  include/sdf/Scene.hh
  include/sdf/Sensor.hh
  include/sdf/Sky.hh
  include/sdf/Sphere.hh
  include/sdf/Surface.hh
  include/sdf/Visual.hh
  include/sdf/World.hh
  src/Model.cc
  src/Root.cc
  src/Root_TEST.cc
  src/World.cc
  test/integration/model/test_model_with_plugin/model.config
  test/integration/model/test_model_with_plugin/model.sdf
  test/integration/model_dom.cc
  test/sdf/include_model_with_plugin.sdf
Labels: 🏯 fortress

#868 Make `computeMergedModelProxyFrameName` public
  include/sdf/parser.hh
  src/Utils.cc
  src/Utils.hh
  src/parser.cc
Labels: 🏯 fortress

#864 Add Ubuntu Jammy CI
  .github/ci/before_cmake.sh
  .github/workflows/ci.yml
Labels: needs upstream release, 🏯 fortress

#827 USD to SDF: Initial commit
  test/usd/materials/textures/FANS_Albedo.png
  test/usd/materials/textures/FANS_Metalness.png
  test/usd/materials/textures/FANS_Normal.png
  test/usd/materials/textures/FANS_Roughness.png
  test/usd/upAxisY.usda
  test/usd/upAxisZ.usda
  test/usd/upAxis_wrong.usda
  usd/include/sdf/usd/UsdError.hh
  usd/include/sdf/usd/usd_parser/USDData.hh
  usd/include/sdf/usd/usd_parser/USDStage.hh
  usd/src/CMakeLists.txt
  usd/src/usd_parser/USDData.cc
  usd/src/usd_parser/USDData_TEST.cc
  usd/src/usd_parser/USDMaterial.cc
  usd/src/usd_parser/USDMaterial.hh
  usd/src/usd_parser/USDStage.cc
  usd/src/usd_parser/USDStage_TEST.cc
Labels: usd

#862 USD -> SDF: Added cmd line tool
  usd/src/CMakeLists.txt
  usd/src/cmd/CMakeLists.txt
  usd/src/cmd/usd2sdf.cc
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: usd

#877 Added light visualize
  include/sdf/Light.hh
  sdf/1.8/light.sdf
  src/Light.cc
  src/Light_TEST.cc
Labels: 🏢 edifice, OOBE 📦✨

#878 Remove Bionic from future releases (Garden+)
  .github/workflows/ci.yml
  usd/include/sdf/usd/sdf_parser/Light.hh
  usd/include/sdf/usd/sdf_parser/World.hh
  usd/src/UsdTestUtils.hh
  usd/src/sdf_parser/Link_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/Sensors_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/World_Sdf2Usd_TEST.cc
Labels: 🌱 garden

#879 🎈 11.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#865 Prepare for 12.4.0~pre1 prerelease
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#863 USD -> SDF: Parse Physics and generated SDF file
  test/usd/upAxisY.usda
  usd/include/sdf/usd/usd_parser/Parser.hh
  usd/src/CMakeLists.txt
  usd/src/cmd/usd2sdf.cc
  usd/src/usd_parser/Parser.cc
  usd/src/usd_parser/USD2SDF.cc
  usd/src/usd_parser/USD2SDF.hh
  usd/src/usd_parser/USDPhysics.cc
  usd/src/usd_parser/USDPhysics.hh
  usd/src/usd_parser/USDPhysics_TEST.cc
  usd/src/usd_parser/USDStage_TEST.cc
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/USDWorld.hh
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: usd

#880 Run cpplint/cppcheck on Focal CI
  .github/workflows/ci.yml
  usd/include/sdf/usd/sdf_parser/Light.hh
  usd/include/sdf/usd/sdf_parser/World.hh
  usd/include/sdf/usd/usd_parser/USDData.hh
  usd/include/sdf/usd/usd_parser/USDStage.hh
  usd/src/UsdTestUtils.hh
  usd/src/sdf_parser/Link_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/Sensors_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/World_Sdf2Usd_TEST.cc
  usd/src/usd_parser/USD2SDF.cc
  usd/src/usd_parser/USDData.cc
  usd/src/usd_parser/USDMaterial.cc
  usd/src/usd_parser/USDStage.cc
  usd/src/usd_parser/USDWorld.cc
Labels: 🏯 fortress

#882 Clean up compiler warnings
  src/Plugin.cc
  src/parser_urdf.cc
  test/integration/joint_dom.cc
  usd/src/cmd/sdf2usd.cc
Labels: 🌱 garden

#883 Use ParserConfig more in parser.cc
  src/parser.cc
  src/parser_private.hh
Labels: 🏯 fortress

#886 Merge 12 -> main
  .github/ci/before_cmake.sh
  .github/workflows/ci.yml
  Changelog.md
  src/parser.cc
  src/parser_private.hh
  test/usd/materials/textures/FANS_Albedo.png
  test/usd/materials/textures/FANS_Metalness.png
  test/usd/materials/textures/FANS_Normal.png
  test/usd/materials/textures/FANS_Roughness.png
  test/usd/upAxisY.usda
  test/usd/upAxisZ.usda
  test/usd/upAxis_wrong.usda
  usd/include/sdf/usd/UsdError.hh
  usd/include/sdf/usd/usd_parser/Parser.hh
  usd/include/sdf/usd/usd_parser/USDData.hh
  usd/include/sdf/usd/usd_parser/USDStage.hh
  usd/src/CMakeLists.txt
  usd/src/cmd/CMakeLists.txt
  usd/src/cmd/usd2sdf.cc
  usd/src/usd_parser/Parser.cc
  usd/src/usd_parser/USD2SDF.cc
  usd/src/usd_parser/USD2SDF.hh
  usd/src/usd_parser/USDData.cc
  usd/src/usd_parser/USDData_TEST.cc
  usd/src/usd_parser/USDMaterial.cc
  usd/src/usd_parser/USDMaterial.hh
  usd/src/usd_parser/USDPhysics.cc
  usd/src/usd_parser/USDPhysics.hh
  usd/src/usd_parser/USDPhysics_TEST.cc
  usd/src/usd_parser/USDStage.cc
  usd/src/usd_parser/USDStage_TEST.cc
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/USDWorld.hh
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: 🌱 garden

#890 Install sdf/1.8 to versioned path
  sdf/1.8/CMakeLists.txt
Labels: 🏢 edifice

#891 Install sdf/1.8 and sdf/1.9 to versioned paths
  sdf/1.8/CMakeLists.txt
  sdf/1.9/CMakeLists.txt
Labels: 🏯 fortress

#892 Prepare for 11.4.1 patch release
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#893 Merge 11 -> 12
  Changelog.md
  include/sdf/Light.hh
  sdf/1.8/light.sdf
  src/Light.cc
  src/Light_TEST.cc
Labels: 🏯 fortress

#894 Merge 12 -> main
  Changelog.md
  include/sdf/Light.hh
  sdf/1.8/CMakeLists.txt
  sdf/1.8/light.sdf
  sdf/1.9/CMakeLists.txt
  src/Light.cc
  src/Light_TEST.cc
Labels: 🏯 fortress

#888 USD to SDF: Fixed gravity magnitude
  usd/src/usd_parser/USDPhysics.cc
Labels: 🏯 fortress, usd

#905 Fixed changelog link
  Changelog.md
Labels: 🏢 edifice

#885 Use more ParserConfig: ParamPassing and sdf::init
  include/sdf/parser.hh
  src/ParamPassing.cc
  src/ParamPassing.hh
  src/Root.cc
  src/parser.cc
Labels: 🏯 fortress

#887 ParserConfig: add ToElementUseIncludeTag policy
  include/sdf/Model.hh
  include/sdf/ParserConfig.hh
  include/sdf/Root.hh
  include/sdf/World.hh
  src/Model.cc
  src/Model_TEST.cc
  src/ParserConfig.cc
  src/Root.cc
  src/World.cc
  test/integration/model_dom.cc
Labels: 🏯 fortress

#896 USD to SDF: Returned errors in USDWorld
  usd/src/usd_parser/USDMaterial.cc
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: 🏯 fortress, usd

#906 USD to SDF: Fixed header guard
  usd/src/usd_parser/USDMaterial.hh
  usd/src/usd_parser/USDPhysics.hh
  usd/src/usd_parser/USDWorld.hh
Labels: 🏯 fortress, usd

#901 USD to SDF: Added some world plugins
  usd/src/usd_parser/USDWorld.cc
  usd/src/usd_parser/usd2sdf_TEST.cc
Labels: 🏯 fortress, usd

#908 require the cli component of ign-utils for usd component
  CMakeLists.txt
  usd/src/cmd/CMakeLists.txt
Labels: 🏯 fortress

#895 USD to SDF: material fixed
  usd/src/sdf_parser/Material_Sdf2Usd_TEST.cc
  usd/src/usd_parser/USDData_TEST.cc
  usd/src/usd_parser/USDMaterial.cc
Labels: 🏯 fortress, usd

#910 Revert some instances of `sdf::ParserConfig` propgation
  src/Model.cc
  src/Root.cc
  src/World.cc
Labels: 🏯 fortress

#916 Change how articulate root API is saved
  usd/src/sdf_parser/Joint_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/Model.cc
  usd/src/sdf_parser/World.cc
Labels: usd

#915 SDF to USD: Fixed material defined in textureImage not in PBR
  usd/src/CMakeLists.txt
  usd/src/Conversions.cc
  usd/src/sdf_parser/Material.cc
  usd/src/sdf_parser/Material_Sdf2Usd_TEST.cc
Labels: 🏯 fortress, usd

#920 Prepare for 12.4.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#917 SDF to USD : support to convert models
  test/sdf/ellipsoid_model.sdf
  usd/src/cmd/CMakeLists.txt
  usd/src/cmd/sdf2usd.cc
  usd/src/sdf_parser/World.cc
  usd/src/sdf_parser/sdf2usd_TEST.cc
Labels: 🏯 fortress, usd

#914 SDF to USD: set UsdPhysicsArticulationRootAPI
  usd/src/sdf_parser/Joint_Sdf2Usd_TEST.cc
  usd/src/sdf_parser/Link.cc
  usd/src/sdf_parser/Model.cc
Labels: 🏯 fortress, usd

#921 DOC 1.9: clarify behavior of //model/model/static
  sdf/1.9/model.sdf
Labels: 🏯 fortress

#871 usd -> sdf: Read transforms
  test/usd/nested_transforms.usda
  test/usd/upAxisZ.usda
  usd/include/sdf/usd/usd_parser/USDData.hh
  usd/include/sdf/usd/usd_parser/USDTransforms.hh
  usd/src/CMakeLists.txt
  usd/src/usd_parser/USDData.cc
  usd/src/usd_parser/USDTransforms.cc
  usd/src/usd_parser/USDTransforms_TEST.cc
Labels: usd

#875 USD -> SDF: Added lights attached to the world
  test/usd/upAxisZ.usda
  usd/src/CMakeLists.txt
  usd/src/usd_parser/USDLight_TEST.cc
  usd/src/usd_parser/USDLights.cc
  usd/src/usd_parser/USDLights.hh
  usd/src/usd_parser/USDStage_TEST.cc
  usd/src/usd_parser/USDWorld.cc
Labels: usd
