Repository gazebosim/sdformat, pull requests merged in 2022-11, with the labels that each got.

#1193 Fix static URDF models with fixed joints
  src/SDFExtension.cc
  src/SDFExtension.hh
  src/parser_urdf.cc
  test/integration/fixed_joint_static.urdf
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🏰 citadel, Gazebo 1️1️

#1194 Merge sdf9 ➡️ sdf12
  Changelog.md
  src/SDFExtension.cc
  src/SDFExtension.hh
  src/parser_urdf.cc
  test/integration/fixed_joint_static.urdf
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🏯 fortress

#1196 Merge sdf12 ➡️ sdf13
  Changelog.md
  src/SDFExtension.cc
  src/SDFExtension.hh
  src/parser_urdf.cc
  test/integration/fixed_joint_static.urdf
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_gazebo_extensions.urdf
Labels: 🌱 garden

#1190 Fix assumptions that `CMAKE_INSTALL_*DIR` variables are relative
  CMakeLists.txt
  cmake/SDFUtils.cmake
  cmake/sdf_config.cmake.in
  cmake/sdformat_pc.in
Labels: 🏰 citadel, Gazebo 1️1️

#1197 Prepare for 9.9.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#1198 Added camera info topic to Camera
  include/sdf/Camera.hh
  sdf/1.7/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🌱 garden

#1199 sdf9 to sdf12
  Changelog.md
  include/sdf/Camera.hh
  sdf/1.7/camera.sdf
  sdf/1.8/camera.sdf
  sdf/1.9/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🏯 fortress

#1200 sdf12 to sdf13
  Changelog.md
  include/sdf/Camera.hh
  python/src/sdf/pyCamera.cc
  python/test/pyCamera_TEST.py
  sdf/1.10/camera.sdf
  sdf/1.7/camera.sdf
  sdf/1.8/camera.sdf
  sdf/1.9/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  test/integration/link_dom.cc
  test/sdf/sensors.sdf
Labels: 🌱 garden

#1195 Check JointAxis expressed-in values during Load
  include/sdf/Error.hh
  include/sdf/parser.hh
  src/Root.cc
  src/parser.cc
  test/integration/joint_axis_dom.cc
  test/sdf/joint_axis_invalid_expressed_in.sdf
Labels: 🌱 garden

#1201 Change default camera_info_topic value to __default__
  sdf/1.7/camera.sdf
  src/Camera.cc
Labels: 🏰 citadel, Gazebo 1️1️

#1203 Added HasLensProjection
  include/sdf/Camera.hh
  python/src/sdf/pyCamera.cc
  python/test/pyCamera_TEST.py
  src/Camera.cc
  src/Camera_TEST.cc
Labels: 🌱 garden

#1205 [backport sdf9] Added HasLensProjection (#1203)
  include/sdf/Camera.hh
  src/Camera.cc
  src/Camera_TEST.cc
Labels: 🏰 citadel, Gazebo 1️1️

#1206 Merge sdf9 ➡️ sdf12
  Changelog.md
  include/sdf/Camera.hh
  sdf/1.7/camera.sdf
  src/Camera.cc
  src/Camera_TEST.cc
Labels: 🌱 garden

#1207 9.10.0~pre2 prerelease
  CMakeLists.txt
Labels: 🏰 citadel, Gazebo 1️1️

#1208 9.10.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️
