Repository gazebosim/sdformat, pull requests merged in 2023-02, with the labels that each got.

#1225 CI workflow: use checkout v3
  .github/workflows/ci.yml
  .github/workflows/macos.yml
Labels: 🏰 citadel, Gazebo 1️1️

#1227 12.7.0~pre1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1213 Allowing relative paths in URDF
  src/parser.cc
Labels: 🏰 citadel

#1228 12.7.0 release
  CMakeLists.txt
Labels: 🏯 fortress

#884 Port embedSdf script from Ruby to Python3 and provide unittests
  sdf/CMakeLists.txt
  sdf/embedSdf.py
  sdf/embedSdf.rb
  src/SDF_TEST.cc
Labels: bug

#1215 Added Airspeed sensor
  include/sdf/AirSpeed.hh
  include/sdf/Sensor.hh
  python/CMakeLists.txt
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyAirSpeed.cc
  python/src/sdf/pyAirSpeed.hh
  python/test/pyAirSpeed_TEST.py
  sdf/1.10/CMakeLists.txt
  sdf/1.10/air_speed.sdf
  sdf/1.10/sensor.sdf
  src/AirSpeed.cc
  src/Airspeed_TEST.cc
  src/Sensor.cc
  test/integration/link_dom.cc
  test/integration/sdf_dom_conversion.cc
  test/sdf/sensors.sdf
Labels: 🌱 garden

#1229 13.3.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1231 Add missing sdf files from xsd generation
  sdf/1.10/CMakeLists.txt
  sdf/1.5/CMakeLists.txt
  sdf/1.6/CMakeLists.txt
  sdf/1.7/CMakeLists.txt
  sdf/1.8/CMakeLists.txt
  sdf/1.9/CMakeLists.txt
Labels: 🌱 garden

#1235 Go back to SDF_ASSERT instead of FATAL_ERROR
  src/Converter.cc
  src/Converter.hh
  src/Converter_TEST.cc
  src/Element.cc
  test/integration/error_output.cc
Labels: 🌱 garden

#1240 Backport the python3 embedSdf script variant
  sdf/CMakeLists.txt
  sdf/embedSdf.py
  src/SDF_TEST.cc
Labels: 🌱 garden

#1233 Add support for merge-includes in worlds
  Migration.md
  sdf/1.10/world.sdf
  src/parser.cc
  test/integration/includes.cc
  test/integration/model/model_for_world_merge_include.sdf
  test/sdf/world_merge_include.sdf
Labels: 🌱 garden

#1241 Fix camera_info_topic default value
  sdf/1.8/camera.sdf
  sdf/1.9/camera.sdf
Labels: 🏯 fortress

#1242 12 -> 13
  .github/workflows/ci.yml
  .github/workflows/macos.yml
  Changelog.md
  sdf/1.8/camera.sdf
  sdf/1.9/camera.sdf
Labels: 🌱 garden, 🎵 harmonic

#1243 Prepare for 12.7.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress
