Repository gazebosim/sdformat, pull requests merged in 2023-03, with the labels that each got.

#1244 Prepare for 13.4.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic

#1245 CI workflow: use checkout v3 in jammy
  .github/workflows/ci.yml
Labels: 🏯 fortress

#1246 Merge sdf12 ➡️ sdf13
  .github/workflows/ci.yml
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic

#1247 Fix camera_info_topic default value in sdf 1.10
  sdf/1.10/camera.sdf
Labels: 🌱 garden, 🎵 harmonic

#1248 Prepare for 13.4.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic

#1252 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel, Gazebo 1️1️

#1253 Merge sdf9 ➡️ sdf12
  COPYING
  LICENSE
  src/parser.cc
Labels: 🏯 fortress

#1254 Merge sdf12 ➡️ sdf13
  COPYING
  LICENSE
  src/parser.cc
Labels: 🌱 garden, 🎵 harmonic

#1249 Add: new error enums to Python
  python/src/sdf/pyError.cc
Labels: 🌱 garden, 🎵 harmonic

#1263 Add missing values in Surace ToElement method
  src/Surface.cc
  src/Surface_TEST.cc
Labels: 🏯 fortress

#1256 Fix Element Set method return value
  include/sdf/Element.hh
  src/Element_TEST.cc
Labels: 🏰 citadel, Gazebo 1️1️
