Repository gazebosim/sdformat, pull requests merged in 2023-08, with the labels that each got.

#1232 Python script to replace ruby xmlschema generator
  .gitignore
  sdf/1.10/CMakeLists.txt
  sdf/1.5/CMakeLists.txt
  sdf/1.6/CMakeLists.txt
  sdf/1.7/CMakeLists.txt
  sdf/1.8/CMakeLists.txt
  sdf/1.9/CMakeLists.txt
  tools/xmlschema.py
  tools/xmlschema.rb
Labels: beta

#1305 Make sure the deprecated kSdfScopeDelimiter still works
  src/Types.cc
  src/Types_TEST.cc
Labels: beta

#1306 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden, 🎵 harmonic

#1307 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden, 🎵 harmonic

#1301 Remove ignition
  python/test/pyModel_TEST.py
  src/Model_TEST.cc
  test/integration/geometry_dom.cc
  test/integration/resolve_uris.cc
  test/sdf/shapes.sdf
  test/sdf/shapes_world.sdf
Labels: beta

#1308 World requires a scene and atmosphere
  python/test/pyWorld_TEST.py
  src/World.cc
  src/World_TEST.cc
Labels: beta, 🌱 garden

#1293 Fix deeply nested merge-include for custom parsed files
  include/sdf/Model.hh
  src/Model.cc
  src/Utils.cc
  src/Utils.hh
  src/World.cc
  src/parser.cc
  test/integration/error_output.cc
  test/integration/interface_api.cc
  test/integration/model/intermediate_model_with_interface_api_1.sdf
  test/integration/model/intermediate_model_with_interface_api_2.sdf
Labels: beta, 🌱 garden

#1311 World: handle name collisions like Model
  Migration.md
  src/World.cc
  test/integration/error_output.cc
  test/integration/world_dom.cc
  test/sdf/world_model_frame_same_name_1_6.sdf
Labels: beta, 🎵 harmonic

#1303 Add python bindings for `sdf::Element` and `sdf::Param`
  include/sdf/Param.hh
  python/CMakeLists.txt
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyElement.cc
  python/src/sdf/pyElement.hh
  python/src/sdf/pyParam.cc
  python/src/sdf/pyParam.hh
  python/src/sdf/pyPrintConfig.cc
  python/src/sdf/pyPrintConfig.hh
  python/src/sdf/pybind11_helpers.hh
  python/test/pyElement_TEST.py
  python/test/pyParam_TEST.py
  python/test/pyPrintConfig_TEST.py
  src/Exception.cc
Labels: beta, 🎵 harmonic

#1313 Merge sdf13 ➡️ main
  .github/workflows/triage.yml
  include/sdf/Model.hh
  python/test/pyWorld_TEST.py
  src/Model.cc
  src/Utils.cc
  src/Utils.hh
  src/World.cc
  src/World_TEST.cc
  src/parser.cc
  test/integration/error_output.cc
  test/integration/interface_api.cc
  test/integration/model/intermediate_model_with_interface_api_1.sdf
  test/integration/model/intermediate_model_with_interface_api_2.sdf
Labels: 🎵 harmonic

#1294 parser.cc update calls to use sdf::Errors output
  include/sdf/Error.hh
  include/sdf/parser.hh
  src/Error.cc
  src/Root.cc
  src/parser.cc
  src/parser_TEST.cc
  src/parser_private.hh
  test/integration/includes.cc
  test/integration/root_dom.cc
Labels: beta, 🌱 garden, 🎵 harmonic

#1166 Joint axis mimic constraints: add ``sdf`` element
  Migration.md
  include/sdf/Error.hh
  include/sdf/JointAxis.hh
  include/sdf/parser.hh
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyError.cc
  python/src/sdf/pyJointAxis.cc
  python/src/sdf/pyJointAxis.hh
  python/test/pyJointAxis_TEST.py
  sdf/1.11/CMakeLists.txt
  sdf/1.11/joint.sdf
  sdf/1.11/mimic.sdf
  src/Joint.cc
  src/JointAxis.cc
  src/JointAxis_TEST.cc
  src/Root.cc
  src/parser.cc
  test/integration/joint_axis_dom.cc
Labels: beta, 🎵 harmonic

#1299 Automatic Moment of Inertia Calculations for Basic Shapes
  include/sdf/Box.hh
  include/sdf/Capsule.hh
  include/sdf/Collision.hh
  include/sdf/Cylinder.hh
  include/sdf/Ellipsoid.hh
  include/sdf/Geometry.hh
  include/sdf/Link.hh
  include/sdf/Model.hh
  include/sdf/ParserConfig.hh
  include/sdf/Root.hh
  include/sdf/Sphere.hh
  include/sdf/World.hh
  sdf/1.11/collision.sdf
  sdf/1.11/inertial.sdf
  src/Box.cc
  src/Box_TEST.cc
  src/Capsule.cc
  src/Capsule_TEST.cc
  src/Collision.cc
  src/Collision_TEST.cc
  src/Cylinder.cc
  src/Cylinder_TEST.cc
  src/Ellipsoid.cc
  src/Ellipsoid_TEST.cc
  src/Geometry.cc
  src/Geometry_TEST.cc
  src/Link.cc
  src/Link_TEST.cc
  src/Model.cc
  src/ParserConfig.cc
  src/ParserConfig_TEST.cc
  src/Root.cc
  src/Root_TEST.cc
  src/Sphere.cc
  src/Sphere_TEST.cc
  src/World.cc
  src/World_TEST.cc
Labels: beta, 🎵 harmonic

#1259 Use relative path in an urdf include to avoid confusion between internal and system headers
  src/urdf/urdf_parser/check_urdf.cpp
  src/urdf/urdf_parser/joint.cpp
  src/urdf/urdf_parser/link.cpp
  src/urdf/urdf_parser/model.cpp
  src/urdf/urdf_parser/pose.cpp
  src/urdf/urdf_parser/urdf_to_graphiz.cpp
  src/urdf/urdf_parser/world.cpp
Labels: beta, 🌱 garden

#1304 Callback based API for Implementing Custom Moment of Inertia Calculators for Meshes
  include/sdf/Collision.hh
  include/sdf/CustomInertiaCalcProperties.hh
  include/sdf/Geometry.hh
  include/sdf/Mesh.hh
  include/sdf/ParserConfig.hh
  sdf/1.11/collision.sdf
  sdf/1.11/inertial.sdf
  src/Collision.cc
  src/Collision_TEST.cc
  src/CustomInertiaCalcProperties.cc
  src/CustomInertiaCalcProperties_TEST.cc
  src/Geometry.cc
  src/Geometry_TEST.cc
  src/Link.cc
  src/Mesh.cc
  src/Mesh_TEST.cc
  src/ParserConfig.cc
  src/ParserConfig_TEST.cc
  src/Root.cc
Labels: beta, 🎵 harmonic

#1315 Prepare for 13.6.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1316 Merge 13 -> 14
  CMakeLists.txt
  Changelog.md
  include/sdf/Error.hh
  include/sdf/parser.hh
  src/Error.cc
  src/Root.cc
  src/parser.cc
  src/parser_TEST.cc
  src/parser_private.hh
  src/urdf/urdf_parser/check_urdf.cpp
  src/urdf/urdf_parser/joint.cpp
  src/urdf/urdf_parser/link.cpp
  src/urdf/urdf_parser/model.cpp
  src/urdf/urdf_parser/pose.cpp
  src/urdf/urdf_parser/urdf_to_graphiz.cpp
  src/urdf/urdf_parser/world.cpp
  test/integration/includes.cc
  test/integration/root_dom.cc
Labels: 🎵 harmonic

#1317 Bugifx: Resolving Inertial Pose in `Collision::CalculateInertial()`
  src/Collision.cc
Labels: beta, 🎵 harmonic

#1318 Prepare for 14.0.0~pre2 Release
  CMakeLists.txt
Labels: 🎵 harmonic
