Repository gazebosim/sdformat, pull requests merged in 2023-09, with the labels that each got.

#1320 Prepare for 12.7.2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1323 Remove hard dependence on ruby
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🎵 harmonic

#1319 Correct spelling of Python variable in CMake
  sdf/1.5/CMakeLists.txt
Labels: beta, 🎵 harmonic

#1331 Prepare for 14.0.0~pre3 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#1332 Prepare for 14.0.0 Release
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🎵 harmonic
