Repository gazebosim/sdformat, pull requests merged in 2023-04, with the labels that each got.

#1266 Merge sdf9 ➡️ sdf12
  include/sdf/Element.hh
  src/Element_TEST.cc
Labels: 🏯 fortress

#1267 JointAxis: improve code coverage in Load()
  src/JointAxis.cc
Labels: 🌱 garden, 🎵 harmonic

#1271 Fix GitHub Actions on macOS
  .github/workflows/macos.yml
Labels: 🏰 citadel, Gazebo 1️1️

#1270 Merge sdf12 ➡️ sdf13
  .github/workflows/macos.yml
  src/Surface.cc
  src/Surface_TEST.cc
  src/gz_TEST.cc
  src/parser_TEST.cc
  src/parser_urdf.cc
  src/parser_urdf_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/deprecated_specs.cc
  test/integration/invalid_force_torque_sensor_lumped_and_reduced.urdf
  test/integration/invalid_force_torque_sensor_massless_child_link.urdf
  test/integration/pose_1_9_sdf.cc
  test/integration/urdf_to_sdf.cc
  test/test_utils.hh
Labels: 🌱 garden, 🎵 harmonic
