Repository gazebosim/sdformat, pull requests merged in 2024-03, with the labels that each got.

#1373 Resolve URIs relative to file path
  include/sdf/ParserConfig.hh
  src/Heightmap.cc
  src/Material.cc
  src/Mesh.cc
  src/ParserConfig.cc
  src/Sky.cc
  src/Utils.cc
  src/Utils.hh
  test/integration/resolve_uris.cc
  test/sdf/media/dummy_cubemap.dds
  test/sdf/media/dummy_material.material
  test/sdf/media/dummy_mesh.dae
  test/sdf/resolve_relative_uris.sdf
Labels: 🌱 garden

#1381 Merge 14 -> main
  include/sdf/ParserConfig.hh
  src/Heightmap.cc
  src/Material.cc
  src/Mesh.cc
  src/ParserConfig.cc
  src/Sky.cc
  src/Utils.cc
  src/Utils.hh
  test/integration/model/double_pendulum.sdf
  test/integration/resolve_uris.cc
  test/sdf/media/dummy_cubemap.dds
  test/sdf/media/dummy_material.material
  test/sdf/media/dummy_mesh.dae
  test/sdf/resolve_relative_uris.sdf
Labels: 🏛️ ionic

#1383 Prepare for 14.1.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#1351 Add bullet and torsional friction DOM
  include/sdf/Surface.hh
  src/Surface.cc
  src/Surface_TEST.cc
  test/integration/surface_dom.cc
  test/sdf/shapes.sdf
Labels: 🏯 fortress

#1382 Add mesh optimization attribute to <mesh>
  include/sdf/Mesh.hh
  sdf/1.11/mesh_shape.sdf
  sdf/1.12/mesh_shape.sdf
  src/Mesh.cc
  src/Mesh_TEST.cc
  test/integration/geometry_dom.cc
  test/sdf/shapes.sdf
Labels: 🏛️ ionic

#1386 Update max_convex_hulls description
  sdf/1.11/mesh_shape.sdf
  sdf/1.12/mesh_shape.sdf
Labels: 🏛️ ionic

#1387 Use relative install paths in CMake
  conf/CMakeLists.txt
  sdf/1.0/CMakeLists.txt
  sdf/1.10/CMakeLists.txt
  sdf/1.11/CMakeLists.txt
  sdf/1.2/CMakeLists.txt
  sdf/1.3/CMakeLists.txt
  sdf/1.4/CMakeLists.txt
  sdf/1.5/CMakeLists.txt
  sdf/1.6/CMakeLists.txt
  sdf/1.7/CMakeLists.txt
  sdf/1.8/CMakeLists.txt
  sdf/1.9/CMakeLists.txt
  src/cmd/CMakeLists.txt
Labels: 🎵 harmonic

#1389 Fix warning with pybind11 2.12
  python/src/sdf/_gz_sdformat_pybind11.cc
Labels: 🎵 harmonic

#1388 Prepare for 14.1.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
