Repository gazebosim/sdformat, pull requests merged in 2024-07, with the labels that each got.

#1453 Fix find Python3 logic and macOS workflow (backport #1367)
  .github/workflows/macos.yml
Labels: 🏰 citadel, Gazebo 1️1️

#1452 Fix macOS workflow (partial backport of #1367)
  .github/workflows/macos.yml
Labels: 🏯 fortress

#1454 Add //sensor/frame_id to SDF spec 1.12
  Migration.md
  include/sdf/Camera.hh
  include/sdf/Sensor.hh
  python/src/sdf/pyCamera.cc
  python/src/sdf/pySensor.cc
  python/test/pySensor_TEST.py
  sdf/1.12/camera.sdf
  sdf/1.12/sensor.sdf
  src/Camera.cc
  src/Camera_TEST.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
Labels: 🏛️ ionic

#1456 Remove deprecated APIs for Ionic
  Migration.md
  include/sdf/Joint.hh
  include/sdf/SDFImpl.hh
  include/sdf/Types.hh
  include/sdf/parser.hh
  src/Joint.cc
  src/Joint_TEST.cc
  src/SDF.cc
  src/SDF_TEST.cc
  src/Types.cc
  src/Types_TEST.cc
  src/parser.cc
Labels: 🏛️ ionic

#1457 Merge sdf14 ➡️ main
  .github/workflows/ci.yml
  Changelog.md
  Migration.md
  include/sdf/Link.hh
  include/sdf/SDFImpl.hh
  include/sdf/Surface.hh
  include/sdf/World.hh
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyBox.cc
  python/src/sdf/pyCapsule.cc
  python/src/sdf/pyCollision.cc
  python/src/sdf/pyCylinder.cc
  python/src/sdf/pyEllipsoid.cc
  python/src/sdf/pyGeometry.cc
  python/src/sdf/pyLink.cc
  python/src/sdf/pyModel.cc
  python/src/sdf/pyParserConfig.cc
  python/src/sdf/pyRoot.cc
  python/src/sdf/pySphere.cc
  python/src/sdf/pySurface.cc
  python/src/sdf/pySurface.hh
  python/src/sdf/pyWorld.cc
  python/test/pyBox_TEST.py
  python/test/pyCamera_TEST.py
  python/test/pyCapsule_TEST.py
  python/test/pyCollision_TEST.py
  python/test/pyCylinder_TEST.py
  python/test/pyEllipsoid_TEST.py
  python/test/pyGeometry_TEST.py
  python/test/pyLink_TEST.py
  python/test/pyParserConfig_TEST.py
  python/test/pyRoot_TEST.py
  python/test/pySphere_TEST.py
  python/test/pySurface_TEST.py
  python/test/pyWorld_TEST.py
  src/Camera.cc
  src/Camera_TEST.cc
  src/Element.cc
  src/Link.cc
  src/Link_TEST.cc
  src/SDF.cc
  src/SDF_TEST.cc
  src/Surface.cc
  src/Surface_TEST.cc
  src/Utils.cc
  src/World.cc
  src/World_TEST.cc
  src/parser.cc
  test/integration/custom_elems_attrs.sdf
  test/integration/plugin_attribute.cc
  test/integration/sdf_custom.cc
  test/integration/surface_dom.cc
  test/sdf/basic_shapes.sdf
  test/sdf/shapes.sdf
  test/sdf/shapes_world.sdf
Labels: 🏛️ ionic

#1458 FrameSemantics: fix NullVertex warnings
  src/FrameSemantics.cc
Labels: 🎵 harmonic

#1459 Revert "FrameSemantics: fix NullVertex warnings (#1458)"
  src/FrameSemantics.cc
Labels: 🏛️ ionic

#1296 Adding Errors structure to XmlUtils
  include/sdf/Error.hh
  src/Converter.cc
  src/Converter.hh
  src/Converter_TEST.cc
  src/ParamPassing.cc
  src/XmlUtils.cc
  src/XmlUtils.hh
  src/XmlUtils_TEST.cc
Labels: 🌱 garden

#1463 Merge sdf13 ➡️ sdf14
  include/sdf/Error.hh
  src/Converter.cc
  src/Converter.hh
  src/Converter_TEST.cc
  src/ParamPassing.cc
  src/XmlUtils.cc
  src/XmlUtils.hh
  src/XmlUtils_TEST.cc
Labels: beta, 🎵 harmonic

#1464 Merge sdf14 ➡️ main
  include/sdf/Error.hh
  src/Converter.cc
  src/Converter.hh
  src/Converter_TEST.cc
  src/ParamPassing.cc
  src/XmlUtils.cc
  src/XmlUtils.hh
  src/XmlUtils_TEST.cc
Labels: 🏛️ ionic
