Repository gazebosim/sdformat, pull requests merged in 2024-01, with the labels that each got.

#1352 Update CI badges in README
  README.md
Labels: 🎵 harmonic

#1354 Prepare for 9.10.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#1356 Merge sdf9 ➡️ sdf12
  Changelog.md
Labels: 🏯 fortress

#1355 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#1357 Merge sdf12 ➡️ sdf13
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  src/CMakeLists.txt
  src/ParamPassing_TEST.cc
Labels: 🌱 garden

#1359 Merge 13 ➡️ 14
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  BUILD.bazel
  Changelog.md
  conf/CMakeLists.txt
  include/sdf/Param.hh
  include/sdf/config.hh.in
  sdf/CMakeLists.txt
  sdf/embedSdf.py
  src/CMakeLists.txt
  src/Capsule_TEST.cc
  src/Cylinder_TEST.cc
  src/ParamPassing_TEST.cc
  src/Plane_TEST.cc
  src/SDF.cc
  src/SDF_TEST.cc
  src/cmd/CMakeLists.txt
  src/gz_TEST.cc
  src/parser_TEST.cc
  test/BUILD.bazel
  test/integration/CMakeLists.txt
  test/integration/converter.cc
  test/integration/default_elements.cc
  test/integration/frame.cc
  test/integration/nested_model.cc
  test/integration/nested_multiple_elements_error.cc
  test/integration/schema_test.cc
  test/integration/toml_parser.hh
  test/test_config.hh.in
Labels: 🎵 harmonic

#1362 In parser config test, use a filename less likely to exist
  test/integration/parser_config.cc
Labels: 🎵 harmonic

#1363 Fix version variable in reference manual PDF filename
  doc/CMakeLists.txt
Labels: 🎵 harmonic

#1365 Fix a little typo in the README.md
  README.md
Labels: 🎵 harmonic

#1367 Fix find Python3 logic and macOS workflow
  .github/workflows/macos.yml
  CMakeLists.txt
Labels: 🏛️ ionic
