Repository gazebosim/sdformat, pull requests merged in 2024-08, with the labels that each got.

#1460 Retry fix for unsafe initialization in graph classes
  src/FrameSemantics.cc
Labels: beta, 🏛️ ionic

#1462 Expand SDF description on link kinematic property
  sdf/1.12/link.sdf
Labels: beta, 🏛️ ionic

#1466 Prepare for sdformat 14.5.0 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#1414 Add optional binary relocatability
  CMakeLists.txt
  include/sdf/InstallationDirectories.hh
  include/sdf/config.hh.in
  src/CMakeLists.txt
  src/InstallationDirectories.cc
  src/SDF.cc
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
Labels: beta, 🎵 harmonic

#1455 Add _state suffix to //state subelements
  Migration.md
  sdf/1.12/CMakeLists.txt
  sdf/1.12/joint_state.sdf
  sdf/1.12/light_state.sdf
  sdf/1.12/link_state.sdf
  sdf/1.12/model_state.sdf
  sdf/1.12/state.sdf
  test/integration/frame.cc
  test/integration/nested_model.cc
Labels: beta, 🏛️ ionic

#1468 Decouple linking to shlwapi from BUILD_TESTING
  src/CMakeLists.txt
Labels: 🎵 harmonic

#1469 Update joinPaths implementation in InstallationDirectories
  src/CMakeLists.txt
  src/InstallationDirectories.cc
Labels: 🎵 harmonic

#1470 Merge sdf14 ➡️ main
  CMakeLists.txt
  Changelog.md
  include/sdf/InstallationDirectories.hh
  include/sdf/config.hh.in
  src/CMakeLists.txt
  src/InstallationDirectories.cc
  src/SDF.cc
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
Labels: 🏛️ ionic

#1471 Ionic Changelog
  Changelog.md
Labels: 🏛️ ionic

#1472 README: update badges for sdf15
  README.md
Labels: 🏛️ ionic

#1473 Prepare for Ionic prerelease
  CMakeLists.txt
  Changelog.md
Labels: 🏛️ ionic

#1477 Prepare for 15.0.0~pre2, update changelog
  CMakeLists.txt
  Changelog.md
Labels: 🏛️ ionic
