Repository gazebosim/sdformat, pull requests merged in 2024-05, with the labels that each got.

#1408 Enable 24.04 CI, remove distutils dependency
  .github/ci/packages.apt
  .github/workflows/ci.yml
  CMakeLists.txt
  examples/CMakeLists.txt
  python/CMakeLists.txt
Labels: 🏛️ ionic

#1409 Fix macOS workflow and backport windows fix
  .github/workflows/macos.yml
  src/Console.cc
  src/cmd/CMakeLists.txt
  src/cmd/cmdsdformat.rb.in
  src/gz_TEST.cc
Labels: 🌱 garden

#1413 (Backport) Enable 24.04 CI, remove distutils dependency (#1408)
  .github/ci/packages.apt
  .github/workflows/ci.yml
Labels: 🎵 harmonic

#1407 Allow empty strings in plugin and custom attributes
  src/Element.cc
  src/Utils.cc
  src/parser.cc
  test/integration/custom_elems_attrs.sdf
  test/integration/plugin_attribute.cc
  test/integration/sdf_custom.cc
Labels: 🎵 harmonic

#1420 Merge sdf14 ➡️ main
  .github/workflows/package_xml.yml
  Changelog.md
  package.xml
  src/Console.cc
  src/JointAxis_TEST.cc
  src/cmd/CMakeLists.txt
  src/cmd/cmdsdformat.rb.in
  src/gz_TEST.cc
Labels: 🏛️ ionic

#1418 Adding cone primitives.
  include/sdf/Cone.hh
  include/sdf/Geometry.hh
  include/sdf/ParticleEmitter.hh
  include/sdf/Visual.hh
  python/CMakeLists.txt
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyCone.cc
  python/src/sdf/pyCone.hh
  python/src/sdf/pyGeometry.cc
  python/src/sdf/pyParticleEmitter.cc
  python/test/pyCollision_TEST.py
  python/test/pyCone_TEST.py
  python/test/pyGeometry_TEST.py
  python/test/pyParticleEmitter_TEST.py
  python/test/pyVisual_TEST.py
  sdf/1.11/CMakeLists.txt
  sdf/1.11/cone_shape.sdf
  sdf/1.11/geometry.sdf
  sdf/1.11/particle_emitter.sdf
  sdf/1.12/CMakeLists.txt
  sdf/1.12/cone_shape.sdf
  sdf/1.12/geometry.sdf
  sdf/1.12/particle_emitter.sdf
  src/Collision_TEST.cc
  src/Cone.cc
  src/Cone_TEST.cc
  src/Geometry.cc
  src/Geometry_TEST.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  src/Visual_TEST.cc
  test/integration/geometry_dom.cc
  test/sdf/basic_shapes.sdf
  test/sdf/shapes.sdf
  test/sdf/shapes_world.sdf
Labels: 🏛️ ionic

#1422 Print auto inertial values with gz sdf --print --expand-auto-inertials
  include/sdf/ParserConfig.hh
  src/Link.cc
  src/ParserConfig_TEST.cc
  src/cmd/cmdsdformat.rb.in
  src/gz.cc
  src/gz_TEST.cc
  test/integration/link_dom.cc
Labels: 🏛️ ionic

#1423 Update default camera instrinsics skew to 0, which matches spec
  python/test/pyCamera_TEST.py
  src/Camera.cc
  src/Camera_TEST.cc
Labels: 🎵 harmonic

#1403 Add <voxel_resolution> SDF element to <convex_decomposition>
  include/sdf/Mesh.hh
  python/src/sdf/pyConvexDecomposition.cc
  python/test/pyMesh_TEST.py
  sdf/1.11/mesh_shape.sdf
  sdf/1.12/mesh_shape.sdf
  src/Mesh.cc
  src/Mesh_TEST.cc
  test/integration/geometry_dom.cc
  test/sdf/shapes.sdf
Labels: 🏛️ ionic

#1425 Add note in migration guide on camera lens intrinsics skew value change
  Migration.md
Labels: 🎵 harmonic

#1426 Merge 12 -> 13
  include/sdf/Link.hh
  include/sdf/Surface.hh
  src/Link.cc
  src/Link_TEST.cc
  src/Surface.cc
  src/Surface_TEST.cc
  test/integration/surface_dom.cc
  test/sdf/shapes.sdf
Labels: 🌱 garden

#1419 Add python binding for no gravity link
  python/src/sdf/pyLink.cc
  python/test/pyLink_TEST.py
Labels: needs upstream release, 🌱 garden

#1427 Add python bindings for bullet and torsional friction
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pySurface.cc
  python/src/sdf/pySurface.hh
  python/test/pySurface_TEST.py
Labels: 🌱 garden

#1428 Merge 13 -> 14
  include/sdf/Link.hh
  include/sdf/Surface.hh
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyLink.cc
  python/src/sdf/pySurface.cc
  python/src/sdf/pySurface.hh
  python/test/pyLink_TEST.py
  python/test/pySurface_TEST.py
  src/Link.cc
  src/Link_TEST.cc
  src/Surface.cc
  src/Surface_TEST.cc
  test/integration/surface_dom.cc
  test/sdf/shapes.sdf
Labels: 🎵 harmonic

#1429 Backport <voxel_resolution> sdf element
  include/sdf/Mesh.hh
  python/src/sdf/pyConvexDecomposition.cc
  python/test/pyMesh_TEST.py
  sdf/1.11/mesh_shape.sdf
  src/Mesh.cc
  src/Mesh_TEST.cc
  test/integration/geometry_dom.cc
  test/sdf/shapes.sdf
Labels: 🎵 harmonic
