Repository gazebosim/sdformat, pull requests merged in 2024-11, with the labels that each got.

#1491 Permit building python bindings separately from libsdformat library
  CMakeLists.txt
  README.md
  python/CMakeLists.txt
Labels: 🏛️ ionic

#1495 Only look for psutil if testing is enabled
  CMakeLists.txt
Labels: 🏛️ ionic, 🪵 jetty

#1498 Prepare for 13.9.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1499 bzlmod support
  BUILD.bazel
  src/Actor_TEST.cc
  src/SDF.cc
  src/SDF_TEST.cc
  src/Sensor_TEST.cc
  src/bazel/InstallationDirectories.cc
  src/parser_urdf_TEST.cc
  test/BUILD.bazel
  test/integration/audio.cc
  test/integration/category_bitmask.cc
  test/integration/cfm_damping_implicit_spring_damper.cc
  test/integration/converter.cc
  test/integration/disable_fixed_joint_reduction.cc
  test/integration/element_memory_leak.cc
  test/integration/fixed_joint_reduction.cc
  test/integration/force_torque_sensor.cc
  test/integration/include.cc
  test/integration/joint_axis_frame.cc
  test/integration/link_light.cc
  test/integration/locale_fix.cc
  test/integration/locale_fix_cxx.cc
  test/integration/material.cc
  test/integration/material_pbr.cc
  test/integration/model_versions.cc
  test/integration/nested_model.cc
  test/integration/parser_error_detection.cc
  test/integration/plugin_attribute.cc
  test/integration/plugin_bool.cc
  test/integration/plugin_include.cc
  test/integration/precision.cc
  test/integration/print_config.cc
  test/integration/provide_feedback.cc
  test/integration/resolve_uris.cc
  test/integration/schema_test.cc
  test/integration/sdf_basic.cc
  test/integration/sdf_custom.cc
  test/integration/unknown.cc
  test/integration/urdf_gazebo_extensions.cc
  test/integration/urdf_joint_parameters.cc
  test/integration/urdf_to_sdf.cc
  test/test_config.hh.in
Labels: 🏛️ ionic, 🪵 jetty

#1492 Support removing the actor, light, or model from the root
  include/sdf/Root.hh
  python/src/sdf/pyRoot.cc
  python/test/pyRoot_TEST.py
  src/Root.cc
  src/Root_TEST.cc
Labels: 🎵 harmonic

#1500 Bazel CI
  .github/workflows/bazel.yml
  .github/workflows/ci.bazelrc
Labels: 🏛️ ionic, 🪵 jetty

#1501 Merge sdf14 ➡️ sdf15
  include/sdf/Root.hh
  python/src/sdf/pyRoot.cc
  python/test/pyRoot_TEST.py
  src/Root.cc
  src/Root_TEST.cc
Labels: 🏛️ ionic, 🪵 jetty

#1502 Prepare for 15.1.0 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🏛️ ionic, 🪵 jetty

#1507 Fix bazel rules for layering_check and parse_headers with clang
  BUILD.bazel
  src/Converter.hh
  src/SDFImplPrivate.hh
  test/BUILD.bazel
Labels: 🏛️ ionic, 🪵 jetty

#1505 Enable header layering checks for bazel build
  .bazelrc
Labels: 🏛️ ionic, 🪵 jetty

#1508 Prepare for release 15.1.1
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🏛️ ionic, 🪵 jetty

#1509 Permit to test when building bindings separately from main library
  python/CMakeLists.txt
Labels: 🏛️ ionic, 🪵 jetty

#1511 SDF 14.6.0 prep
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic
