Repository gazebosim/sdformat, pull requests merged in 2024-04, with the labels that each got.

#1390 Parse kinematic property in link
  include/sdf/Link.hh
  src/Link.cc
  src/Link_TEST.cc
  test/integration/link_dom.cc
  test/sdf/double_pendulum.sdf
Labels: 🏛️ ionic

#1391 Merge 14 -> main
  Changelog.md
  conf/CMakeLists.txt
  python/src/sdf/_gz_sdformat_pybind11.cc
  sdf/1.0/CMakeLists.txt
  sdf/1.10/CMakeLists.txt
  sdf/1.11/CMakeLists.txt
  sdf/1.12/CMakeLists.txt
  sdf/1.2/CMakeLists.txt
  sdf/1.3/CMakeLists.txt
  sdf/1.4/CMakeLists.txt
  sdf/1.5/CMakeLists.txt
  sdf/1.6/CMakeLists.txt
  sdf/1.7/CMakeLists.txt
  sdf/1.8/CMakeLists.txt
  sdf/1.9/CMakeLists.txt
  src/cmd/CMakeLists.txt
Labels: 🏛️ ionic

#1394 Param_TEST: Check return values of Param::Get/Set
  src/Param_TEST.cc
Labels: 🎵 harmonic

#1396 Merge sdf14 ➡️ main
  src/Param_TEST.cc
Labels: 🏛️ ionic

#1398 Added Python wrapper to ConvexDecomposition
  python/CMakeLists.txt
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyConvexDecomposition.cc
  python/src/sdf/pyConvexDecomposition.hh
  python/src/sdf/pyMesh.cc
  python/test/pyMesh_TEST.py
Labels: 🏛️ ionic

#1399 Added kinematic methods to Python Link wrapper
  python/src/sdf/pyLink.cc
  python/test/pyLink_TEST.py
Labels: 🏛️ ionic

#1397 Change behavior of Param::Get<bool>
  Migration.md
  include/sdf/Param.hh
  python/test/pyParam_TEST.py
  src/Param_TEST.cc
Labels: 🏛️ ionic

#1374 Add package.xml, fix `gz sdf` tests on Windows
  .github/workflows/package_xml.yml
  package.xml
  src/Console.cc
  src/cmd/CMakeLists.txt
  src/cmd/cmdsdformat.rb.in
  src/gz_TEST.cc
Labels: 🎵 harmonic

#1404 Backport pybind11 warning fix
  python/src/sdf/_gz_sdformat_pybind11.cc
Labels: 🌱 garden

#1402 Fix trivial warning on 24.04 for JointAxis_TEST.cc
  src/JointAxis_TEST.cc
Labels: 🎵 harmonic

#1405 Prepare for 14.2.0 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic
