Repository gazebosim/sdformat, pull requests merged in 2024-06, with the labels that each got.

#1430 Prepare for 12.8.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1432 Merge 12 -> 13
  Changelog.md
Labels: 🌱 garden

#1433 Prepare for 13.7.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1435 Merge 13 -> 14
  Changelog.md
Labels: 🎵 harmonic

#1436 Added World::ActorByName:
  include/sdf/World.hh
  python/src/sdf/pyWorld.cc
  src/World.cc
  src/World_TEST.cc
Labels: 🌱 garden

#1437 Prepare for 14.3.0 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#1434 Remove Cone shape from particle emitters
  include/sdf/ParticleEmitter.hh
  python/src/sdf/pyParticleEmitter.cc
  python/test/pyParticleEmitter_TEST.py
  sdf/1.11/particle_emitter.sdf
  sdf/1.12/particle_emitter.sdf
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
Labels: 🏛️ ionic

#1406 Add custom attribute to custom element in test
  test/integration/custom_elems_attrs.sdf
  test/integration/sdf_custom.cc
Labels: 🎵 harmonic

#1415 Add Cone as a primitive parametric shape.
  include/sdf/Cone.hh
  include/sdf/Geometry.hh
  include/sdf/Visual.hh
  python/CMakeLists.txt
  python/src/sdf/_gz_sdformat_pybind11.cc
  python/src/sdf/pyCone.cc
  python/src/sdf/pyCone.hh
  python/src/sdf/pyGeometry.cc
  python/test/pyCollision_TEST.py
  python/test/pyCone_TEST.py
  python/test/pyGeometry_TEST.py
  python/test/pyVisual_TEST.py
  sdf/1.11/CMakeLists.txt
  sdf/1.11/cone_shape.sdf
  sdf/1.11/geometry.sdf
  src/Collision_TEST.cc
  src/Cone.cc
  src/Cone_TEST.cc
  src/Geometry.cc
  src/Geometry_TEST.cc
  src/Visual_TEST.cc
  test/integration/geometry_dom.cc
  test/sdf/basic_shapes.sdf
  test/sdf/shapes.sdf
  test/sdf/shapes_world.sdf
Labels: 🎵 harmonic

#1441 Prepare release 14.4.0
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#1370 Backport #1367 to Garden: Fix find Python3 logic and macOS workflow
  CMakeLists.txt
Labels: 🌱 garden

#1443 Prepare for 13.8.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1295 SDF.cc update calls to use sdf::Errors output
  include/sdf/SDFImpl.hh
  src/SDF.cc
  src/SDF_TEST.cc
Labels: 🌱 garden

#1445 workflows/ci.yml fix push branch regex
  .github/workflows/ci.yml
Labels: 🎵 harmonic

#1444 Merge sdf13 ➡️ sdf14
  Changelog.md
  include/sdf/SDFImpl.hh
  include/sdf/World.hh
  python/src/sdf/pyWorld.cc
  src/SDF.cc
  src/SDF_TEST.cc
  src/World.cc
  src/World_TEST.cc
Labels: 🎵 harmonic

#1440 Added SetHeightMap and Heighmap to Geometry Python binding
  python/src/sdf/pyGeometry.cc
  python/test/pyGeometry_TEST.py
Labels: 🎵 harmonic

#1447 Disable latex and class hierarchy generation
  doc/CMakeLists.txt
  doc/sdf.in
Labels: 🏛️ ionic
