Repository gazebosim/sdformat, pull requests merged in 2025-01, with the labels that each got.

#1523 Remove unncessary <iostream> includes
  include/sdf/Error.hh
  include/sdf/Exception.hh
  src/Console.cc
  src/Element.cc
  src/FrameSemantics.cc
  src/SDF.cc
Labels: 🏛️ ionic, 🪵 jetty

#1524 Add non-const overload for Root::Model() getter
  include/sdf/Root.hh
  python/src/sdf/pyRoot.cc
  src/Root.cc
  src/Root_TEST.cc
Labels: 🏛️ ionic, 🪵 jetty

#1521 ci.yml: run cppcheck, cpplint on noble
  .github/workflows/ci.yml
Labels: 🏛️ ionic, 🪵 jetty

#1529 Add missed spec version 1.12 in the sdf_descriptions target
  sdf/1.11/root.sdf
  sdf/1.12/root.sdf
  sdf/CMakeLists.txt
Labels: 🏛️ ionic, 🪵 jetty

#1528 Add entry to Migration guide about the updated auto-inertia behavior
  Migration.md
Labels: 🏛️ ionic, 🪵 jetty

#1530 Add entry to Migration guide about the updated auto-inertia behavior -> sdf14
  Migration.md
Labels: 🎵 harmonic

#1532 Prepare for 9.10.2 Release
  CMakeLists.txt
  Changelog.md
Labels: Gazebo 1️1️
